### ISSUE TITLE
Pokerbot bug/suggestion

### ISSUE THREAD

**Issue by alitadark** [Masuzu/GBFPokerBot#1]
Hi,

After using the bot for a few hours, i've noticed that if the bot hits 128k it'll be unlikely to continue (had a jack on 128k and the bot stopped)

could you make a version of the bot that will always attempt to max the pot as I find the bot stopping at 128k a lot.

thanks!

**Comment by Masuzu** [comment]
Hi alitadark,

Actually, this feature is already implemented!

In the GBFPokerBot.ini file, you will find the 2 following parameters under the [Bet] section:

```
# When the bet is greater than or equal to this value, the bot will forfeit when the probability of getting a higher or lower card is lower than 0.7
PayoutCut=128000
# The bot will forfeit when the bet is greater than or equal to this value, unless you draw a 2 or A
MaxPayoutCut=1024000
```

which should be self-explanatory. Just bump up PayoutCut to more than 1 million and you will have the  desired behaviour!

Cheers
