### ISSUE TITLE
Issue with finding the ok button

### ISSUE THREAD

**Issue by ekcs0915** [Masuzu/GBFPokerBot#100]
![image](https://cloud.githubusercontent.com/assets/16605209/24353895/c4c60df0-132a-11e7-8ff1-73bc620f8fcb.png)

I am still receiving the same error, with the windows as shown. I have tried with and without viramate, with the same results. Thank you in advance.

**Comment by Masuzu** [comment]
It looks like a scaling issue. Please make sure to disable any scaling:
https://poker-bot.azurewebsites.net/en/Home/Requirements
