### ISSUE TITLE
gbf have a new mechanic to detect bot?

### ISSUE THREAD

**Issue by po456asd** [Masuzu/GBFPokerBot#101]
long time ago it was a captcha after a long peroid of botting. 
but now what i got is it will make a game broke, can't click everything.
if you are botting bot will stuck and close so that they will know you are bot
you need to refresh the page to prevent banned and bot again.
.
this is how i got banned last time, no captcha just game stuck.
.
i just want to share to you, because this banned is not the captcha as before.

**Comment by Masuzu** [comment]
You may get stuck when there is a new version of the game available (a popup will appear). That's the only situation where this may happen (a screenshot of other situtations to share around would be much appreciated - should they exist).
The likelyhood for this to happen is small though and if you do not bot for several hours in a row everyday everytime it should hardly ever happen. I sometimes ran into the same case but I had no issue at all during the past months.

**Comment by po456asd** [comment]
last time i set timeout to just 1.30 hr, i don't think it too long for bot.
next time i'll just streaming to some website to save a video while botting so i can share to you. 
thanks :)

**Comment by Masuzu** [comment]
Nice, thank you.

**Comment by Yalzy** [comment]
how to set timeout ?

**Comment by po456asd** [comment]
in GBFPokerBot.ini file
it was TimeLimitInSeconds= xxxxx
set it in second

**Comment by po456asd** [comment]
i still recorded but no banned lately.
but i got another problem

i got this window only one time 
![image](https://cloud.githubusercontent.com/assets/13596788/24762820/ad812462-1b19-11e7-8784-d7c3721655b7.png)

everytime it just be like this. [ after 2hr of botting just like that time^ [i set timeout to 2 hr]]
[game froze] [bot stopped]
![image](https://cloud.githubusercontent.com/assets/13596788/24762853/ce88d25e-1b19-11e7-9632-142ee14667d8.png)
![image](https://cloud.githubusercontent.com/assets/13596788/24762896/f41aff74-1b19-11e7-93d4-39bd67393fc2.png)
![image](https://cloud.githubusercontent.com/assets/13596788/24762908/ff9de7ee-1b19-11e7-8a32-9fc38a6494e8.png)
![image](https://cloud.githubusercontent.com/assets/13596788/24763023/52acaca4-1b1a-11e7-954a-b001e257c64b.png)

**Comment by Masuzu** [comment]
Hi,
This is the expected behaviour when TimeLimitInSeconds= xxxxx is reached.
Stay safe. Sessions of 2 hours are fine.

**Comment by po456asd** [comment]
well i think it should show stat like the first picture right?
but whenever it reach time limit the bot just show gamefroze

i will upload a video for you. i'll post it here.

**Comment by po456asd** [comment]
here you go. 
https://drive.google.com/drive/u/0/folders/0B4AQ7NyN6b_VTXhpUVhuc0l6RGc

**Comment by Masuzu** [comment]
Oh, probably the stats window must be overlapped by another window. I will look into it a bit later, as it is not critical.

**Comment by vinchazz** [comment]
so is gamefroze sent by the game or by the bot ? because i just get it today, i highly hope it's not a ban from the game

**Comment by yurigama** [comment]
How many hours do u play it for a day ? to be safe

**Comment by po456asd** [comment]
@yurigama less than 3 hr maybe 2 - 2.30hr would be good
