### ISSUE TITLE
Unregistered User Error

### ISSUE THREAD

**Issue by kazoy1000** [Masuzu/GBFPokerBot#104]
I believe I followed the steps correctly.

Generate Serial Num -> Register -> Download App -> Download Key -> Pasted key on directory.

But I still get this:
![pokerbot](https://cloud.githubusercontent.com/assets/26902692/24662856/eae07782-1988-11e7-8840-5086de1b37dc.png)

I even bought a one month subscription. What did I do wrong?

**Comment by Masuzu** [comment]
Hello,
Does your generated serial number match the one on https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber
If so, please make sure that your key.txt file is encoded in UTF-8 but it should already be the case.

**Comment by kazoy1000** [comment]
Yes it does, I've regenerated it many times and pasted it on the Update serial number and always gives me the No Update notice in red text. And I've checked the key.txt in notepad++ saying that it's UTF8 without BOM. I've tried changing it to UTF8 only and when I do that the command terminal immediately closes after the alert box of "brought to you by".

**Comment by Masuzu** [comment]
I can debug it if you send me at gbfpokerbot@gmail.com the serial number for the computer where you are experiencing issues as well as the contents of your key.txt file.

**Comment by Masuzu** [comment]
By the way, my  own key file is encoded in UTF8 only. The only possible reason which I can find would be firewall settings. But that's weird.

**Comment by kazoy1000** [comment]
I've sent the credentials through the said email. We're you able to test it yet?

**Comment by Masuzu** [comment]
Sorry about the delay. I received the information and will do it in 5-6 hours from now.

**Comment by Masuzu** [comment]
Will follow-up individually

**Comment by Masuzu** [comment]
Thank you very much for the feedback!
The version 2.8.1 will now creates a file with the correct serial number which should be used, so you can copy and paste it more easily.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
