### ISSUE TITLE
Serial code; 4 Days cooldown

### ISSUE THREAD

**Issue by MasoAri** [Masuzu/GBFPokerBot#107]
Hi, recently tried this software, looked promising. After renewing from trial license to a month license I tried it first on a different device unfortunately it wasn't working well on it, so I decided to just use it on my laptop since that's where it last worked, sadly I can't change the serial number on my account to use it on this laptop. I made a different account before to test it on this laptop since I was confused about the serial code before, I thought it was tied only to one device so I made a new account for that. Is there any way you can somehow reset the cooldown? Want to use it as soon as possible, thanks. Sorry too, if it's not the right section for this or anything.

Cheers.

**Comment by Masuzu** [comment]
Hi,

I can reset for you the cooldown so you can change again the serial number on the management page. Could you please send me to gbfpokerbot@gmail.com the email you used to register an account (the email on which the licence is active)? I will apply the change within 6 hours.

**Comment by MasoAri** [comment]
Hi,

I sent an email to that e-address using the email I used for the account with active license, if that's what you were asking for, I'm sorry if I've misunderstood.

**Comment by Masuzu** [comment]
Got it, perfect, thank you.
I have just made the change. Let me know if you still run into issues.
