### ISSUE TITLE
VCRUNTIME140 error ver. 2.8.0

### ISSUE THREAD

**Issue by 0inkypig** [Masuzu/GBFPokerBot#108]
Hi, Just downloaded the new version and it gives me this error. I installed the program recommended in the patch notes
![capture](https://cloud.githubusercontent.com/assets/27046270/24826086/7b878148-1c60-11e7-9f20-ef46fd661eb3.PNG)

**Comment by Masuzu** [comment]
Hi,

This is exactly what it means. There are 2 versions of https://www.microsoft.com/en-us/download/details.aspx?id=48145
One for 32 and one for 64 bit.
In your case you need the 32bit version (vcredist_x86) since you are using the client.

**Comment by Masuzu** [comment]
https://github.com/Masuzu/GBFPokerBot/issues/106
