### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by Noctikz** [Masuzu/GBFPokerBot#11]
Alright, so I have all the settings to what you specified, followed the steps to launch the bot and game.

I always get an error message.  This has been happening since Day 1 of release and is current as of version 1.7.4b

![error](https://cloud.githubusercontent.com/assets/22664705/19161345/6b7ca812-8bc1-11e6-8ec9-1958fd6e53b7.png)

**Comment by Masuzu** [comment]
Hello,

If I am not mistaken, it looks like you are  playing the Japanese version of the game.
If that is the case, please make sure that the Language setting is set to 'jp' in the GBFPokerBot.ini file.

Also make sure that you are using the game settings described here: https://poker-bot.azurewebsites.net/en/Home/Requirements and that you are on the screen where the 'OK' button is visible, as explained in https://poker-bot.azurewebsites.net/en/Home/QuickStart

This error only means that you are not following one of those steps.

**Comment by Noctikz** [comment]
I am currently playing from game.granbluefantasy.jp with my language setting set to English.  I currently have it set to 'en' within the .ini file and that is when I am getting the error.  When I switch back to jp, I now get the there is no granblue window open.

I followed all the game settings and requirements as well as have the "good" game screen setup.

Within the Data Folder, I do not have a 'PokerTableHook.png' file.

I am currently running on an Windows 10 Operating system with an i7 Processor.

**Comment by Masuzu** [comment]
You might want to try to run this version:
https://drive.google.com/open?id=0Bxx3PpakQ2jGSzdpLVUtWWFra1U
When you run it, you should have a second window pop up with a view of your board and the positions of the cards identified.

**Comment by Noctikz** [comment]
Just tried that version now, am I supposed to be running it much like the previous versions?
This is what I get, only 1 window.

![error4](https://cloud.githubusercontent.com/assets/22664705/19196990/b25233a0-8c85-11e6-95d8-4444110c26a7.png)

**Comment by Masuzu** [comment]
Yes you are supposed to be running it like the other versions after replacing the GBFPokerBot.exe file with the one I provided. You are not supposed to re-register or re-activate a licence.
It is working fine with other people.

**Comment by Noctikz** [comment]
Yea, I replaced the .exe file with the one you gave me and it keeps telling me I need to update the file(which I can't because it leads to a dead link).  I close that window and it brings me to the picture I linked above.

**Comment by Masuzu** [comment]
If you get the licence info window popping up you should get it in the first place too with the non-modified GBFPokerBot.exe file.

**Comment by Noctikz** [comment]
It's weird, I thought that too but it keeps happening.  I'd replace the unmodified version with the modified one and the message always pops up.

**Comment by Masuzu** [comment]
Can you send me the serial number you have using the exe file GBFPokerBotSerialNumberGenerator.exe and the 4 first characters of your email please? I will fix the issue with the licence.

**Comment by Noctikz** [comment]
Serial Number: 8a11dc80b100afda0ab35e994ed133774401e21e9eebacbdbdcc055bb1c458ac1504cedd5c713caa963e6ca9e5c5643226af37b375be1864356e6ca3d28c6333

4 Char Email: tae0

**Comment by Masuzu** [comment]
Thank you.
That serial number is correct indeed. You must have changed your password recently then, in which case you need to redownload the archive from the website to have a new valid key.txt file.

**Comment by Noctikz** [comment]
Alright, so I downloaded the latest archive(should be ver 1.8.0 right?) and tried that version out, the same error still shows up.  I tried replacing the unmodified .exe with the modified one and I still get the unregistered account issue.  I'm not sure what I'm doing wrong or what's going on here.

Also if it matters, I checked the key.txt file from an older version and compared it to the newer version, the key is still the same.  Not sure if that has anything to do with it.

**Comment by Masuzu** [comment]
Did you allow the program to run in your Firewall settings?

**Comment by Noctikz** [comment]
Yea, I've allowed the program already.

**Comment by Masuzu** [comment]
There should not be any problem if the serial number on https://poker-bot.azurewebsites.net/en/Manage
is the same as the one generated by your serial number generator. It looks like you are the only one in this situation.

**Comment by Noctikz** [comment]
Alright, so when I go and check the serial number generator, the serial numbers are not the same anymore.

New serial number on the generator is: 35bbe54fc158b3e428f3a02386f06064ea12d483613b49eb5a1c1e7d442eaa87626ebddc9cc9b8d84a3e25196fd8c7dbab4121347fd79fa0db6568252dd23e53

**Comment by Noctikz** [comment]
Alright, so after trying everything possible, I don't think this is going to work.  Oh well, thank you for trying to help.
