### ISSUE TITLE
Bot dont play continue while got J in 128k

### ISSUE THREAD

**Issue by Yalzy** [Masuzu/GBFPokerBot#110]
I bot for a long time i saw something that not make senses , 
when bot got 128 k bot will not continue when J but continue with 4 

why ? 

they are same win rate  but why not continue J but still continue 4

**Comment by Masuzu** [comment]
Hello,

This is intended unless you increase the parameter `PayoutCut`:
# When the bet is greater than or equal to this value, the bot will forfeit when the probability of getting a higher or lower card is lower than 0.7
