### ISSUE TITLE
PokerBot stopped working

### ISSUE THREAD

**Issue by Gin12312** [Masuzu/GBFPokerBot#111]
When I run the pokerbot, the executable crashes and stops working. Is there a setting that I messed up on or missed?

**Comment by Masuzu** [comment]
Hello,
I am afraid I won't be able to help with this request without further information.
Make sure you extracted the bot and installed the requirements (VC++ 2015 redistributable packages) beforehand.

**Comment by Gin12312** [comment]
I deleted everything and started from scratch. Had to extend a month to test since trial expired but it works now!

**Comment by Masuzu** [comment]
Good to hear that it works now!
