### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by bayleaph** [Masuzu/GBFPokerBot#112]
No matter what browser I attempt to download in I get Failed-Network error on my part, but only for the new version, I can download older versions fine.

**Comment by po456asd** [comment]
if you dont mind please try again

https://www.dropbox.com/s/wmf4w3b42yjvono/GBFPokerBot_v2.8.1_x86.zip?dl=1

**Comment by po456asd** [comment]
or just use this and select download 2.8.1
https://www.dropbox.com/sh/2jmkt9evh25b5lo/AABvsm_eAnqrlJ0UrG1aaZMqa?dl=0&lst=
![image](https://cloud.githubusercontent.com/assets/13596788/25222202/03a42a92-25e2-11e7-9a21-af19574c0019.png)

**Comment by bayleaph** [comment]
yep tried both methods and still getting failed - network error, but I can download 2.7 just fine from the drop box.

**Comment by po456asd** [comment]
https://drive.google.com/drive/folders/0B4AQ7NyN6b_VZ0xWTXZtSkV5Sk0?usp=sharing

**Comment by Masuzu** [comment]
Thank you @po456asd 
Closing this.
