### ISSUE TITLE
Can't renew license on Zooeybot

### ISSUE THREAD

**Issue by RayKng** [Masuzu/GBFPokerBot#116]
I can't renew my license on Zooeybot, it simply doesn't give me the option to do so, and neither could I use the free trial. As far as I understand it is separate from the poker bot, which I do use and currently have. Is it simply not public yet, or is something wrong with the coding, or is it simply my account.

![screenshot1](https://cloud.githubusercontent.com/assets/27907697/25368552/0a262020-2932-11e7-94b6-d10749c0dc19.png)
![screenshot2](https://cloud.githubusercontent.com/assets/27907697/25368553/0a284de6-2932-11e7-9a3f-e6f6b657abca.png)

**Comment by Masuzu** [comment]
Hello,
There is no ZooeyBot available for now and the licence will be separate from the poker bot one.
