### ISSUE TITLE
about playing poker bot on another computer

### ISSUE THREAD

**Issue by chuongcyper** [Masuzu/GBFPokerBot#117]
Hello guys, i had download poker bot on another computer, but when i started, it say "unregistered user" although i have change the serial number and download key. Am i missing sth?

**Comment by Masuzu** [comment]
Hello,
When you run the bot, a text file called serial_number will be created in the same folder as the executable file, containing the serial number to use for this computer. There have been some rare reports of mismatching serial numbers between the one from the serial number generator and the one which you need to use actually.

**Comment by chuongcyper** [comment]
well i try to edit the file with the serial on the website, but it keeps auto change itself?

**Comment by Masuzu** [comment]
It is not supposed to change on a same computer.
