### ISSUE TITLE
Advisor not accurate 

### ISSUE THREAD

**Issue by Korwaislife** [Masuzu/GBFPokerBot#118]
While playing a high or low, the advisor don't count the cards and have the standard %, this make that tool less usefull... 
On this screen, i got a 8 at the start and a 8 some cards later, but the probability are the same, it's not possible.
http://i.imgur.com/K0WtlbV.png

Another problem is at the launch of the advisor : http://i.imgur.com/Nw2hlOd.png
I have the latest version who is on the site. If i close this message with the cross on the window it close entirely the program, i have to close it with the cross on the task bar.

Sorry if my english is bad.

**Comment by Masuzu** [comment]
Hi,
Thank you for reporting these two issues. It looks like a bug and I will fix this when I have some time.

**Comment by Masuzu** [comment]
The version 2.8.2 should address this issue: https://poker-bot.azurewebsites.net/en/Home/PatchNotes
