### ISSUE TITLE
Email Password recovery

### ISSUE THREAD

**Issue by Aetherick** [Masuzu/GBFPokerBot#12]
Hello,

I'm assuming I need to buy another license to run this on my second pc (a laptop). I did the trial period to see if my laptop could run it, but I forgot what email I used/the password. Is there a way recover/reset the password?

Thanks.

**Comment by Masuzu** [comment]
Hello,

Thank you for reporting in.
There is no password recovery or reset for now I am afraid. This is something I will update as soon as I can so you can reset your password.

**Comment by Masuzu** [comment]
Hello,

I am pleased to announce that you can now reset your password through the login page:
https://poker-bot.azurewebsites.net/en/Account/Login

**Comment by Aetherick** [comment]
Hi,

I can confirm the password reset does seem to work. Unfortunately it didn't fix my problem for my laptop. It appears that the email I thought I used to try the free trial on my laptop wasn't the one. Is it possible for me to send you my serial number in order to figure out how I can login and extend the license?

Thanks.
