### ISSUE TITLE
Cuda compute capability

### ISSUE THREAD

**Issue by kilorn** [Masuzu/GBFPokerBot#120]
Hello, just tried to run your poker bot but I got this error, 
![sans titre](https://cloud.githubusercontent.com/assets/28185661/25554395/a472827a-2ccc-11e7-9826-4bc8b70183d9.png)

So I searched about Cuda compute capability and it seems my graphic card have only a 2.1 compute capability (https://developer.nvidia.com/cuda-gpus (GeForce 820M)).
So, is there no way for me to run your bot ? Thanks.

**Comment by Korwaislife** [comment]
Wich version are you running ? the latest don't need the cuda, my computer don't have a nvidia graphic card and i can run it.

**Comment by Masuzu** [comment]
Hello,
The CUDA version is not available anymore, for now.

**Comment by kilorn** [comment]
I was using the 2.5 version, I downloaded the lastest (2.8.2) but my licence is no more active so the bot close just after I run it.
Is there a way to just check if I can run it without having an active licence ?

**Comment by Masuzu** [comment]
You can't without an active licence. You can check your licence status on https://poker-bot.azurewebsites.net/en/Manage
