### ISSUE TITLE
Wrong card detection

### ISSUE THREAD

**Issue by lightmeme789** [Masuzu/GBFPokerBot#121]
Hello, just tried to run your poker bot but I got this error.
http://prntscr.com/f2i3dm.

What this error ?

**Comment by Masuzu** [comment]
Hello,
Eaxctly what it says: the card identification scores that you get are very low (below 0.85). This should not happen if the initial calibration looks like this:
http://imgur.com/a/Kfnze
You can check the calibration result by opening the PokerTableHook_5.png picture which is created in the same folder as the executable when the bot is initialized.
