### ISSUE TITLE
Trying to renew licence

### ISSUE THREAD

**Issue by feeeeels** [Masuzu/GBFPokerBot#123]
Hey i tried renewing the licence by paying through card twice. Both times the thing loaded and came up with a green tick, then it just closes and nothing happened. Ive tried once 9 hours ago and now and both times it did not work.

**Comment by po456asd** [comment]
have tired with difference browser yet?

**Comment by Masuzu** [comment]
Hi,

You can try the Paypal option which also supports credit cards. No feeds are charged if the transaction failed.
