### ISSUE TITLE
Initialization 4/6

### ISSUE THREAD

**Issue by Rkdheishins** [Masuzu/GBFPokerBot#125]
it says pleasse make sure to open the chrome dev tools by pressing f12

and its clearly open but not recognizing it...

lost what to do at this point...
![capture](https://cloud.githubusercontent.com/assets/28521755/25789164/57283c2e-3363-11e7-97b9-95716e0a7f49.PNG)

**Comment by Masuzu** [comment]
There are 2 extensions.
https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)
