### ISSUE TITLE
unregistered user?

### ISSUE THREAD

**Issue by 1000yen** [Masuzu/GBFPokerBot#13]
hi i have recently bought your licence, after todays update i wasn't able to use the bot as it told me im an unregistered user and asked me to buy a new licence again
![vfd](https://cloud.githubusercontent.com/assets/22692927/19208565/49b064a8-8d2e-11e6-9fc4-1ab3d9124dcb.jpg)

**Comment by Masuzu** [comment]
Hello,

Could you please send me the first 4 characters of your email and the serial number generated by https://drive.google.com/open?id=0Bxx3PpakQ2jGQTA3WU9ZZ1JOTTQ so I can sort this out?
Thank you in advance.

**Comment by 1000yen** [comment]
do i write it here? or do i email u? if its emalinign can i have your email? thx XD

**Comment by Masuzu** [comment]
Here is fine, I'll delete the message after

**Comment by 1000yen** [comment]
alirte the first 4 character of my email is xian my serial number is d57fb39803d5eb6762abe0c8175abaa787496f0d04230626a509d3c78251c0bfcd691f99cb6ac6159f4cb006876c2bac0fc866f53008a96a652eee3c6241e725

**Comment by Masuzu** [comment]
It should be fixed now.

**Comment by 1000yen** [comment]
alrite tyvm ^^

**Comment by Masuzu** [comment]
Awesome :)
