### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by ilovepokerbots** [Masuzu/GBFPokerBot#136]
Hi ive bought the full version already and been using it sine 3 March, this morning 4/6/2017 i received an error like this when opening up [](url)http://i66.tinypic.com/2h5m92q.png

**Comment by ilovepokerbots** [comment]
http://imgur.com/a/R61Ny 
sorry broken link

**Comment by Masuzu** [comment]
Did you extract the archive? This happens if you do not.

**Comment by ilovepokerbots** [comment]
it's not working for me i extracted and its doing the same thing
Is there a way i can get a new code / reinstall a working version with this? 

    Pada Senin, 3 Juli 2017 3:09, Masuzu <notifications@github.com> menulis:
 

 Did you extract the archive? This happens if you do not.—

**Comment by Masuzu** [comment]
It looks like a calibration issue.
https://poker-bot.azurewebsites.net/en/Home/Requirements
Closing as there is no issue if you follow the requirements as the other users do.
