### ISSUE TITLE
Unregistered user too

### ISSUE THREAD

**Issue by omegaher** [Masuzu/GBFPokerBot#14]
HI Masuzu

I have some problem.
Yesterday i bough your license but i cannot run software. It look like 1000yen user. 

My e-mail : bankgama_______@
My Serial : 0eb769b3________________________________________________________________________________________________

Best Regards

**Comment by 1000yen** [comment]
i had mine fixed yesterday but it happened again today 
![htrhrth](https://cloud.githubusercontent.com/assets/22692927/19217341/e9398e3c-8e0a-11e6-8b2b-ac8ce4ce9d6d.jpg)

**Comment by Masuzu** [comment]
Hello,

I will do something about the option to change the serial number within 24 hours.
@1000yen Did you run a Windows update between yesterday and the moment you ran again into these licence error messages?

**Comment by 1000yen** [comment]
@Masuzu no i don't think i had a windows update between yesterday and the moment i run the pokerbot again it just happen aft i woke up and try to run it

**Comment by Masuzu** [comment]
Done, you can now change again your serial number as before.
However, some restrictions such as the frequency of such changes will be enforced in the future.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
