### ISSUE TITLE
Flagged as trojan by Windows Defender

### ISSUE THREAD

**Issue by hivehum** [Masuzu/GBFPokerBot#140]
![new canvas](https://user-images.githubusercontent.com/26695058/27566091-b15e386e-5ab0-11e7-829a-1f8590c3e272.png)

the zip files are being flagged but the unpacked files aren't. idk if you can do anything about this but i figure it's fair to let you know

**Comment by kiralasani** [comment]
I am having this same issue, but Chrome is refusing to download, and giving me this message:
GBFPokerBot_v2.8.2_x64.zip Failed - Virus detected
https://prntscr.com/fpdxt2
https://prntscr.com/fpdy0v

**Comment by Masuzu** [comment]
I have to disable manually Windows Defender to access the download link:
https://github.com/Masuzu/GBFPokerBot/issues/79

**Comment by kiralasani** [comment]
My windows defender is disabled, but I still get this message.
