### ISSUE TITLE
Could you upload the bot to another site plz?

### ISSUE THREAD

**Issue by akira9311** [Masuzu/GBFPokerBot#141]
Chinese government blocked the Dropbox. I cannot access to the download since I left the states.
Please help me or at least refund please....

**Comment by Masuzu** [comment]
Hi,

Here is a google drive download link for the 32 nit version:
https://drive.google.com/open?id=0Bxx3PpakQ2jGbDg3QTd4MDY3R00

**Comment by Masuzu** [comment]
https://www.vpnmentor.com/blog/how-to-access-dropbox-in-china/

**Comment by Masuzu** [comment]
Direct GitHub download link

[GBFPokerBot_v2.8.2_x64.zip](https://github.com/Masuzu/GBFPokerBot/files/1119259/GBFPokerBot_v2.8.2_x64.zip)

I will upload the 32 bit client later.

**Comment by Masuzu** [comment]
Direct download link for the 32 bit client:

[GBFPokerBot_v2.8.2_x86.zip](https://github.com/Masuzu/GBFPokerBot/files/1120265/GBFPokerBot_v2.8.2_x86.zip)
