### ISSUE TITLE
Serial number already taken

### ISSUE THREAD

**Issue by shamwowzer** [Masuzu/GBFPokerBot#145]
I was trying to register for an account to try out the software, but the serial number generated from the serial number generator seems to already be in use. I changed the last number to allow the account to register, but the same issue arises when I try to change it back to the correct generated one. Is there any way to generate a new number? Since it seems to be locked to my computer.

![serial_no_issue](https://user-images.githubusercontent.com/29875925/27810615-96afc4a4-602a-11e7-9bc9-cc583247e6ec.png)

**Comment by Masuzu** [comment]
Sorry, there is no way to get a second serial number.
Someone else or you are already using this serial number. Unless they did not purchase a licence you won't be able to reuse this serial number for a certain while.
