### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by Dewten** [Masuzu/GBFPokerBot#147]
I used the trial version about three days ago, then decided to buy it yesterday.
I tried to download the zip again because I didn't have the files on the pc anymore, but it looks like the link is down. I thought it would be temporary and decided to wait for the following day but it looks like the 64 and 32-bit versions as well as the old versions are still down.

I didn't think it was worth it to create a ticket on github for something this small, but I couldn't find a way to contact you directly. Care to provide a mirror download?
![untitled](https://user-images.githubusercontent.com/12978332/27931185-a539a0be-6299-11e7-83a9-b32513a025dc.jpg)

**Comment by Masuzu** [comment]
Hello,

Do you happen to live in China?
Here are alternative download links: https://github.com/Masuzu/GBFPokerBot/issues/141
