### ISSUE TITLE
Unregistered User

### ISSUE THREAD

**Issue by StanFusion** [Masuzu/GBFPokerBot#15]
Hi,
After my pc updated i had a  serial code that was different to the one i registered with would it be possible to change the serial code?
![capture](https://cloud.githubusercontent.com/assets/22717619/19216058/fed6ce56-8de9-11e6-8f67-02d23734b9b7.PNG)

**Comment by Masuzu** [comment]
Done, you can now change again your serial number as before.
However, some restrictions such as the frequency of such changes will be enforced in the future.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
