### ISSUE TITLE
Serial number update

### ISSUE THREAD

**Issue by saerukun** [Masuzu/GBFPokerBot#155]
I updated today the serial number to test Zooey bot before buying it, and i changed the serial code to the one thats generated on my laptop, could you please let me change it again at the previous one? I already bought the month fee for the bot and i don't wanna waste 4 days of it. Thanks

![zooeybot code issue](https://user-images.githubusercontent.com/23666959/29092061-3b33fa38-7c85-11e7-96d1-8101380c5aa2.png)

**Comment by Masuzu** [comment]
Hello,

The 4 day limit was temporarily lifted.

**Comment by saerukun** [comment]
Thanks a lot!
