### ISSUE TITLE
Trial - Hook Error

### ISSUE THREAD

**Issue by syusaki** [Masuzu/GBFPokerBot#157]
I DL'd the trial version, but I can't seem to get it to work. The suggestions listed in the error window I should've already taken care of in the quickstart guide. I have the key file, the serial number generator and file match. I have a low-end i5 processor so I tried changing the parameters to the ones seen in this video [here](https://www.youtube.com/watch?annotation_id=annotation_3385858023&feature=iv&src_vid=3mk7gmLAlcg&v=vtW7fTDJANk). I think I have the game window open correctly, so I'm not sure what's wrong. I've attached a screenshot for reference.
![poker](https://user-images.githubusercontent.com/31190720/29497827-366540d4-85a4-11e7-9213-394b7e6ac56a.png)

**Comment by debunotkuro** [comment]
I have the exact same problem, I also tried it on two different computers.
![hook error](https://user-images.githubusercontent.com/31936178/30396134-7d5b9326-987d-11e7-8177-8bc007ebb670.JPG)

**Comment by Masuzu** [comment]
Hi,
I have not yet implemented the Windows scaling check as done in Zooey Bot but in the future, I will do it to avoid this kind of error due to a misconfiguration on the user side.
