### ISSUE TITLE
Error"You are not connected to Internet"

### ISSUE THREAD

**Issue by joezhoucn** [Masuzu/GBFPokerBot#158]
Hello,
I have download the Poker bot from github.
And open the GBFPokerBot.exe

the program remind me that "You are not connected to Internet"
But I really access to the internet.

so what i can do to use the program.

![Uploading no internet connection error.png…]()

**Comment by joezhoucn** [comment]
I am in CHINA,
Is there any chinese users?

**Comment by Masuzu** [comment]
I am very sorry for the very late reply, this should have been fixed in a past release intended for Chinese users running into this issue.

**Comment by Masuzu** [comment]
The version 2.8.3 which has just been released addresses this issue http://poker-bot.azurewebsites.net/en/PatchNotes#2-8-3
