### ISSUE TITLE
"Unregistered" and unable to change Serial Number.

### ISSUE THREAD

**Issue by Iakustim** [Masuzu/GBFPokerBot#16]
I run the bot frequently on both my desktop and my laptop because sometimes I'm not always at home where my desktop it, but would like to keep the bot running and in a place here I can keep an eye on it (such as the laptop). 

Depending on which I run it on, I have to change the serial number on my account so that it correctly detects the license that I bought, on whichever system I want to run the bot on. However, the "change serial" option in the manage account menu has disappeared (I noticed it missing at the same time v1.8 came out) locking the bot to my laptop, and rendering my desktop as an "unregistered user."

If you don't want constant serial swapping, then that's fine, but I would like to (if that's the case), have my account locked to my desktop rather than my laptop, but I'm unable to switch it back at the moment.

**Comment by Masuzu** [comment]
Hello,

I will do something about the option to change the serial number within 24 hours.

**Comment by Masuzu** [comment]
Done, you can now change again your serial number as before.
However, some restrictions such as the frequency of such changes will be enforced in the future.
