### ISSUE TITLE
Zooey bot slave mode

### ISSUE THREAD

**Issue by Rkdheishins** [Masuzu/GBFPokerBot#162]
ever since the new co op mode got updated, im unable to do coop with my alt.

so i start it up normally and when it trys to attack with slave it says zooey bot has stooped working 

on the other hand when i change the settings to have main attack first, it does so then moves to slave and immediately stops working and the same error message pops up "zooey bot has stooped working"

i dont use any scrips or have any lua codes, just plain auto attacking, going on 3 hours trying to figure this out and search open and closed ticked with nothing helping.

any help would be awesome thank you!

**Comment by Rkdheishins** [comment]
anything would be helpful

**Comment by Rkdheishins** [comment]
anything at all...

**Comment by Masuzu** [comment]
Hi,
These crashes were fixed already in a last release and I have been running the slave mode today.

**Comment by Masuzu** [comment]
+ wrong github

**Comment by Rkdheishins** [comment]
if they were fixed then ill buy another month, ill get back to you here shortly

**Comment by Rkdheishins** [comment]
its working for me again, glad i bought another month, thank you so much for your hard work!
