### ISSUE TITLE
Applying for adding another regular device

### ISSUE THREAD

**Issue by Gem11137** [Masuzu/GBFPokerBot#163]
Hi, 

I'm Gem, a current user who have been used for several months. Most of the time I need to use the zoeybot both on my laptop with me and my PC at home. function of changing serial number works for me but the 4 days' cool down seems too long for me and caused quite a few inconveniences. Could I have my account eligible for 2 certain devices? I can provide information you required via email.

Thanks,
Gem

**Comment by Masuzu** [comment]
Hi,

I am sorry but the 4 day cooldown is there for that particular reason, among other ones.
