### ISSUE TITLE
Cant download the PokerBot

### ISSUE THREAD

**Issue by Xleonq** [Masuzu/GBFPokerBot#164]
hi,i was new person here and just sign up my acc with trial
but when i try to download the PokerBot(64-bit) it give me error 429 (image provide below)
can someone help?

![ss 2017-10-07 at 01 16 47](https://user-images.githubusercontent.com/32578285/31290052-b832eb4c-aafd-11e7-9c9c-574fd5b0adf0.png)

**Comment by Masuzu** [comment]
There are GitHub alternative download links.
