### ISSUE TITLE
Bot keeps telling me I am unregistered after i renew my license.

### ISSUE THREAD

**Issue by violafayde** [Masuzu/GBFPokerBot#167]
Hi, I am encountering this frustrating issue where I am unable to update the serial number for the bot after I renewed the license just recently. I download a new key.txt and place it in, but it tells me that i am unregistered. I try to update the serial number with the new serial number generated, but it simply tells me that 'name (keycode) is already taken.'
Please help.

**Comment by aramus007** [comment]
same here :(

**Comment by Masuzu** [comment]
Hi,

A section on the getting started page were added to avoid these kind of problems. The documentation regarding this part was updated for ZooeyBot while it was not for GBFPokerBot.
Now everything should be up-to-date:
GBFPokerBot: https://poker-bot.azurewebsites.net/en/Home/Requirements
ZooeyBot: https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation#first-run

**Comment by Masuzu** [comment]
The likelihood that 2 different users share the same serial number is very low. Old users who never had an active licence for more than <undisclosed amount of time> should be automatically deleted when a user with a licence tries to take reuse their serial number.
