### ISSUE TITLE
i edited the ini file and its telling me that i am unregistered

### ISSUE THREAD

**Issue by aramus007** [Masuzu/GBFPokerBot#168]
when i go in to update my serial key they said that i just updated my serial key 4 days ago. which i did. it was working fine till i updated the ini file please help

**Comment by Masuzu** [comment]
Hi,

A section on the getting started page were added to avoid these kind of problems. The documentation regarding this part was updated for ZooeyBot while it was not for GBFPokerBot.
Now everything should be up-to-date:
GBFPokerBot: https://poker-bot.azurewebsites.net/en/Home/Requirements
ZooeyBot: https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation#first-run
