### ISSUE TITLE
cant download poker bot @ dropbox plz fix it

### ISSUE THREAD

**Issue by straufe** [Masuzu/GBFPokerBot#169]
![screenshot 15](https://user-images.githubusercontent.com/33593698/32697385-ed63bfae-c7c1-11e7-858f-5bfdd2cad77d.png)
![screenshot 14](https://user-images.githubusercontent.com/33593698/32697384-e965c212-c7c1-11e7-9d0f-cb716af751f0.png)

**Comment by Masuzu** [comment]
It is not an issue.
The error message clearly says why.
Alternative GitHub download links are already provided.
