### ISSUE TITLE
Still Unregistered user

### ISSUE THREAD

**Issue by omegaher** [Masuzu/GBFPokerBot#17]
Hi Masuzu
I still cannot use. After new version & i changed my serial number.

![untitled](https://cloud.githubusercontent.com/assets/22716346/19220803/1bf3cafe-8e60-11e6-90c3-c027c9cfccb9.png)

New Serial number was different Old Serial number.

My e-mail : bankgama_____@hotmail.com

**Comment by Masuzu** [comment]
Hi,

The new serial is different from the old one indeed.

The current serial number you registered is:
bb7d53f3644d22a356cfc6f0bf78694dc26b50eb3c6c7a7fbf735a7dd2243d6f10ac5c3af0b9b74c0e55919d0278811734a96c270ad43bb10ffad20ad206397a

Make sure it is the same as the one from generated by https://poker-bot.azurewebsites.net/en/Account/GBFPokerBotSerialNumberGenerator 

Step 1: download https://poker-bot.azurewebsites.net/en/Account/GBFPokerBotSerialNumberGenerator and obtain a new serial number (it should be different from the old one)
Step 2: go to https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber and paste the new serial number
Step 3: go to https://poker-bot.azurewebsites.net/en/Manage and download again the archive

**Comment by helpmepoker** [comment]
having the same problem, followed the steps and when I try updating my serial number it says it's taken?
![d824276274024aac999cbe8e85865893](https://cloud.githubusercontent.com/assets/22738279/19227817/3b1882a2-8e84-11e6-971c-487a2665b550.png)

**Comment by Masuzu** [comment]
It would mean you or someone else you must know already created an account using this serial number, which is not supposed to happen under normal circumstances.

**Comment by helpmepoker** [comment]
so i got stolen from...? is there no way to solve this...

**Comment by helpmepoker** [comment]
am i fucked.. 😢 ?

**Comment by helpmepoker** [comment]
what's going on then?

**Comment by feelsbadman2** [comment]
I got the same problem as helpmepoker.  So is there a solution to fix this? Because I am the only one who use my PC and I just woke up and this happened to me.
![dsadsd](https://cloud.githubusercontent.com/assets/22740916/19230175/46748fc8-8efd-11e6-9206-ebdcf5d00e87.jpg)

**Comment by Masuzu** [comment]
Hello both of you, and all the other users who may run into such errors.
Got it, I will patch the issue within 24 hours.

**Comment by helpmepoker** [comment]
Thank you Masuzu! Always nice to see you being so helpful, keep up the good work man! 😄

**Comment by omegaher** [comment]
Sry for my late Masuzu.
Today is monday. I use my laptop in my office and it can run your software after i change serial number (Laptop).
When i back home, i change my serial number (PC) but it's still show me Unregistered user.
I think tomorrow i will bring my laptop to my home.

**Comment by Masuzu** [comment]
Hello @omegaher ,
Something is slightly wrong with the serial number generation at the moment and I identified the issue. I will fix it and notify you when it is done.

**Comment by Masuzu** [comment]
Hello everyone,

The version 1.8.2 should fix the issues related to serial numbers.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
Please let me know if something is off before I close the ticket. 
I apologize for the trouble.

Cheers

**Comment by helpmepoker** [comment]
Everything works fine, thanks Masuzu.

**Comment by omegaher** [comment]
Thx Masuzu
I can swap serial number my PC & my Laptop.
Everything is ok. Thx again Masuzu.

**Comment by Masuzu** [comment]
Awesome, thank you for reporting back.
