### ISSUE TITLE
License suddenly expired when change serial number

### ISSUE THREAD

**Issue by redmd** [Masuzu/GBFPokerBot#173]
Just like the title.

I buy a license for 1 month yesterday. 

I change serial number to use it on another machine. But license suddenly expired when I do it. I change it again to use on my original machine. BUT I need to wait for 4 days to change it again..

need help ASAP.

**Comment by Masuzu** [comment]
Hello,
If you change the serial number of the management page, I can confirm that licence do not expire, thanksfully!
The 4 day restriction was temporarily lifted so you can change again your serial number freely. Please do so.
