### ISSUE TITLE
Poker table hook error

### ISSUE THREAD

**Issue by Shintaro27071997** [Masuzu/GBFPokerBot#174]
Need help.
![untitled](https://user-images.githubusercontent.com/34410751/33802557-4dd602fc-ddac-11e7-973a-4ca854c54bd6.png)

**Comment by Masuzu** [comment]
Hi, this is again a calibration issue.
The documentation states what is needed.
If it still fails, then try again with another new starting hand. I can happen, but rarely enough to be ignored.
