### ISSUE TITLE
Unable to download latest version

### ISSUE THREAD

**Issue by Xeph88** [Masuzu/GBFPokerBot#178]
Hi I just paid for a month of the bot and realized I couldn't update the latest version:

![image](https://user-images.githubusercontent.com/26945729/34805027-a6f55644-f6b6-11e7-8adf-7890a9527a0f.png)

I realized there is another dude with the same problem that haven't been answer for half a month..... If the site is down could you at least close it and refund us the amount?

**Comment by Masuzu** [comment]
Hi,
I'm not sure how people can miss this...
![image](https://user-images.githubusercontent.com/5464705/34892556-fece4cb2-f7d9-11e7-8968-83c2f6e8d22d.png)
