### ISSUE TITLE
0xc000007b error

### ISSUE THREAD

**Issue by aciri** [Masuzu/GBFPokerBot#18]
![explorer_2016-10-11_19-50-06](https://cloud.githubusercontent.com/assets/22776041/19281842/51e7a59e-8fec-11e6-8e17-490279925838.png)

Tried:
Running as administrator
Compability mode (every option)

Using:
Win7 x64bit

**Comment by Masuzu** [comment]
Hello @aciri,

I am quite surprised to see you running into this error. Could you please install Visual C++ Redistributable Packages for Visual Studio 2013 from https://www.microsoft.com/en-us/download/details.aspx?id=40784 (make sure you choose the 32 bit version: vcredist_x86.exe) and try running the exe file again please?

**Comment by aciri** [comment]
![dwm_2016-10-12_14-33-19](https://cloud.githubusercontent.com/assets/22776041/19310155/059c2a0a-9089-11e6-9703-cde0935b4b75.png)

I now have 24h trial, though I've run into another problem.

Tried:
Running as Admin
Compability mode (every option)
