### ISSUE TITLE
Not working after the 2.9.2 update

### ISSUE THREAD

**Issue by wkykaos** [Masuzu/GBFPokerBot#183]
the bot just not working after the update, it just work perfectly for the last version
![2018y02m05d_040948564](https://user-images.githubusercontent.com/36138207/35781951-a63e9cf0-0a2b-11e8-9f0f-9677273e8021.png)

**Comment by cfb90** [comment]
I am having the same problem

**Comment by ScavengerPr0** [comment]
Yes im also having the same problem
bot worked yesterday on patch 2.9.1

**Comment by fortehk** [comment]
having the same proble. the previous version (2.9.1) worked perfectly.

**Comment by 6DX** [comment]
me too，the same problem

**Comment by wkykaos** [comment]
welldone, its over one day and no response from the dev, and i see same problem happen to sarasa bot, why not just simply rollback to the previous version or refund me

**Comment by KENTOG** [comment]
I'm also having the same issue. I get stuck at the initial hook and then the captcha noise plays on loop.

**Comment by steve1316** [comment]
Chiming in to say that I'm encountering the same issue. And I just decided to renew my license today too..

**Comment by Masuzu** [comment]
Hello,

I did not bump up the version but fixed the provided ZIP:
Please redownload and replace the contents of your folder with the one provided here:
https://github.com/Masuzu/GBFPokerBot/releases/tag/2.9.2

**Comment by ScavengerPr0** [comment]
works now TY

**Comment by ScavengerPr0** [comment]
it seems to have a problem when during double up it gets an Ace then it gets a hook error

**Comment by ScavengerPr0** [comment]
it also seems to have way more desync way more often

**Comment by Masuzu** [comment]
There is no change in behaviour regarding this part.

**Comment by ScavengerPr0** [comment]
ok i think it was my internet lagging a bit seems so far so good TY once again
