### ISSUE TITLE
Verification email never recieved - unable to use serial now.

### ISSUE THREAD

**Issue by AzurNep** [Masuzu/GBFPokerBot#184]
It's been about 48 hours or so, I can safely say I believe that verification emails don't play nice with @aol domains. So i'm stuck unable to use the serial for my hardware/laptop since it's tied to an email that cannot verify, I politely request, since it is impossible to resend, or change the email one can be sent to. To delete my account with the aol address so I can use my serial with a different email address? 

The account unable to verify's email is
namedown@aol.com

**Comment by Masuzu** [comment]
Hello,
I have just deleted the account associated with this email so you can retry and register.
