### ISSUE TITLE
The serial number changed itself

### ISSUE THREAD

**Issue by Flare07** [Masuzu/GBFPokerBot#185]
As the topic said, yesterday I used Zooey without any problem.
But, today my Zooey is not working anymore, become unregistered and my serial changed itself.

This is like 3-4th time this has happened. Still don't know the cause.
Normally, I can stand with it because it happened like once a week.
But right now, I can't change the serial because of 4 days cooldown.
And we have the upcoming Fenrir&Cerberus rerun today.

At least, please lift the cooldown for me. So I can have fun farming Fimbul.
![report](https://user-images.githubusercontent.com/36288473/36011725-d864eb0e-0d8b-11e8-8a88-63651861dd34.png)

**Comment by Masuzu** [comment]
Hello,
I can't make the change right now but will do so in 10 hours from now or so.
