### ISSUE TITLE
The serial number changed

### ISSUE THREAD

**Issue by Tatsukimi** [Masuzu/GBFPokerBot#187]
The bot was fine yesterday, today i log in and when i try to open the bot, say it i not a registered user and i can't change the serial number because of 4 days cooldown. 
![screenshot 46](https://user-images.githubusercontent.com/15004919/36751640-7ee87066-1bdf-11e8-8ca8-632d650f5875.png)

![screenshot 47](https://user-images.githubusercontent.com/15004919/36751676-9645b7be-1bdf-11e8-98ff-df99857d33d2.png)

**Comment by Masuzu** [comment]
Hello, the limitation was temporarily lifted.
