### ISSUE TITLE
Problem on payment cant buy the bot

### ISSUE THREAD

**Issue by nyky2311** [Masuzu/GBFPokerBot#191]
I tried buy the bot today but i get this error on payment. 

Your account cannot currently make live charges. If you are the site owner, please activate your account at https://dashboard.stripe.com/account/details to remove this limitation. If you are a customer trying to make a purchase, please contact the owner of this site. Your transaction has not been processed.

**Comment by Masuzu** [comment]
Hello,
This is more troublesome than I expected it to be and will take some time to resolve while an alternative can be found.

**Comment by Masuzu** [comment]
https://github.com/Masuzu/GBFPokerBot/issues/192

**Comment by Masuzu** [comment]
Paypal was reintroduced

**Comment by nyky2311** [comment]
Hi i got it poker and sarassa, please can you send me a lua for sarassa ground zero 3 skill to leech ? i tried learn make lua but not working. thanks.

________________________________
De: Masuzu <notifications@github.com>
Enviado: quarta-feira, 14 de março de 2018 10:36:31
Para: Masuzu/GBFPokerBot
Cc: nyky2311; Author
Assunto: Re: [Masuzu/GBFPokerBot] Problem on payment cant buy the bot (#191)


Paypal was reintroduced
