### ISSUE TITLE
Can't Start

### ISSUE THREAD

**Issue by pokerblues** [Masuzu/GBFPokerBot#193]
![helpmee](https://user-images.githubusercontent.com/37517979/37571299-f45a6826-2b35-11e8-9298-bafa1f6c4792.png)
Hello! Could you help me out? I really want it to work but if it still can't work, I would like a refund. I have tried all the settings and steps you mentioned but I still can't get it to work. :(

**Comment by pokerblues** [comment]
![helpmee2](https://user-images.githubusercontent.com/37517979/37572504-e6f0534c-2b46-11e8-8d4d-e79eb02aa0da.png)
I tried zooming in by an additional 10% (Total 110%) now. and it finally detects the cards, but now it doesn't detect the "OK" button. Help please!~

**Comment by pokerblues** [comment]
Sorry! I made a mistake, it was my bad. I forgot to change scaling to 100% under my PC settings, Its working as intended now. Thanks!

**Comment by Masuzu** [comment]
Hello,
You should set the zoom to 100% and check that you disabled the auto resizing feature in your GBF settings.
