### ISSUE TITLE
Stop at Initial Hook and Unable to unpack Advisor

### ISSUE THREAD

**Issue by eichisama** [Masuzu/GBFPokerBot#195]
Hi Again,

I'm having issue as per title, can't get it to work since it just sat there doing nothing.
![stuck](https://user-images.githubusercontent.com/33214703/37576481-a4a2fdb6-2b67-11e8-9cdc-ff7f235e1588.JPG)

Also got below error when trying to add the advisor to chrome.
![extensions](https://user-images.githubusercontent.com/33214703/37576488-aadf8190-2b67-11e8-8089-ded5a812ada2.JPG)

Using latest version PokerBOT and Chrome 64.

**Comment by pokerblues** [comment]
I also have to same exact issue and the program didn't do anything

**Comment by pokerblues** [comment]
Is there still any solution for this? Couldn't run the bot for an entire day already

**Comment by Masuzu** [comment]
Hello,
I will look into it as soon as I can. There seems to be a regression which was introduced.

**Comment by Masuzu** [comment]
About the fact that you seem to be stucked after the initialization, I confirmed with several computers that it is working as intended.
![image](https://user-images.githubusercontent.com/5464705/37643566-3ea91134-2c21-11e8-9a6a-44923082acc8.png)

**Comment by eichisama** [comment]
I dunno if there anything else that need to change in the config. but here's mine

`[General]
# Possible values: jp, en. Default to en when the string is malformed
Language=en
# When you click on a button, the underlying request (bet higher, continue or stop for instance) is sent to the server and the game in your brower window won't update its state before the server acknowledges the request and the server response is received by your browser. For instance, if I have a 3-second delay (lag) due to a poor Internet connection, the game won't react for at least 3 seconds whenever I click on a button. This setting configures the minimum delay before the bot takes any action (determining the cards drawn or determining the position of the buttons for instance).
GameLatencyCompensationInMs=400
# The bot will stop after the given parameter no matter what and display a statistics menu. Close this menu to reset the timer and  resume the bot.
TimeLimitInSeconds=7200
DetectionThreshold=0.85
HigherOrLowerDetectionThreshold=0.85
# The bot will wait after each click on a button for a random amount of time between 0 and the given value. A value of 0 will ignore this feature. Values are given in milliseconds.
MaxWaitTimeAfterActionInMs=0

[Bet]
# Supported values: 10, 100 and 1000. Default will be 1000 is another value is given. Please make sure you input a correct value.
StartingBet=10
# When the bet is greater than or equal to this value, the bot will forfeit when the probability of getting a higher or lower card is lower than 0.7
PayoutCut=128000
# The bot will forfeit when the bet is greater than or equal to this value, unless you draw a 2 or A
MaxPayoutCut=1024000
# If set to true, the bot will go for a straight or a flush when the hand is one card away from such winning hands, even if there is one pair among the drawn cards. This does not affect hands which are guaranteed to proceed to higher-or-lower.
FavourHigherPayingHandOnOnePair=true

[Inputs]  
MouseSpeed=170
DelayInMsBetweenMouseDownAndUp=40
# The bot will stop when you press the given key. The default key is escape. Please refer to https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx (the values on this page are given in hexadecimal base).
ExitKeyCode=27
# The bot will enter the pause mode and display basic statistics when you press the given key. The default key is F10. Please refer to https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx (the values on this page are given in hexadecimal base).
PauseKeyCode=121
# After the bot moves the cursor to the target position, wait for the given duration before performing the click
WaitTimeInMsBeforeClickInput=50

[MotionCapture]
# The bot considers the animation (see the definition of 'animation' above) currently played ends when during the given number of consecutive browser screen captures, there is no motion detected
ConsecutiveFramesWithoutMovement=30
# Minimum delay between 2 consecutive browser window screen captures
MinDelayInMsBetweenFrames=5
MaxWaitTimeInMsBetweenActions=4000

[Debug]
MotionCapture=false
Hooks=true
Clicks=false

[Alerting]
# Relative path to the mp3 or wav file to play when the game freezes for more than 10 seconds, which happens when a captcha window appears for instance.
CaptchaNotificationSoundPath=captcha_notification.mp3
# Number of times the captcha notification sound is played when the game freezes for more than 10 seconds, which happens when a captcha window appears for instance.
NumNotifications=9999`

Kindly advise :)

**Comment by Masuzu** [comment]
Even though the version did not change, I updated the package: https://github.com/Masuzu/GBFPokerBot/releases/tag/2.9.3
This addresses both issues, namely the "getting stuck" after the initialization and the issue with loading the extension.
Please note that the extension is not required for normal use, and is not compatible anymore with Chrome 65.0.3325. More information about this [here](https://github.com/Masuzu/ZooeyBot/issues/625).

**Comment by eichisama** [comment]
Thanks, I've tested it and it's working flawlessly now :+1:

**Comment by pokerblues** [comment]
Yeah it works now, thanks!
