### ISSUE TITLE
gbfporker can't be used.

### ISSUE THREAD

**Issue by ruinon** [Masuzu/GBFPokerBot#198]
@Masuzu 

I'm Japanese, so I can't speak English well, so a translation tool is used and it's written.

A license was renewed a short while ago, but it couldn't be used.
A serial number renewal was also done, but an error occurs and isn't made.
I'm being scolded. An error I resemble also generates the previous time, and money becomes wasteful.
I request correspondence. I request supplementation for the money which became wasteful.

![asdazcx](https://user-images.githubusercontent.com/37949452/38160264-cc13ebde-34f5-11e8-9cd7-042a565ddd35.jpg)
![aaaaaa](https://user-images.githubusercontent.com/37949452/38160265-cc3be5c6-34f5-11e8-8a41-a7742c55a2df.jpg)
![asdas](https://user-images.githubusercontent.com/37949452/38160266-cc662d54-34f5-11e8-921f-f4a80961e3f6.jpg)

**Comment by Masuzu** [comment]
Hello,
Sometimes the serial number generator has some issues and does not give you the proper serial number.
When you run GBFPokerBot.exe, a file named `serial_number.txt` is created and the contents of this file contains the actual serial number which you should set in the management page.

![image](https://user-images.githubusercontent.com/5464705/38193600-1b05b230-3673-11e8-965b-c71c912ecbe1.png)

However, if you happen to still get the same issue, it means that someone else already uses this serial number.
In this case, if you write down here the serial number which you are trying to use, I can see if I can delete the previously associated account, but only _if_ this account is inactive.
