### ISSUE TITLE
Unable to work

### ISSUE THREAD

**Issue by WildKaiser** [Masuzu/GBFPokerBot#20]
Hi there. I've done everything as instructed but there still seems to be a problem. Screenshots for your reference please. Windows zoom is at 100%. 

If it's at 125%, the bot may sometimes hook successfully but the mouse always seems to be in the wrong position so it clicks on nothing. It does move around though. 

![screenshot 2016-10-12 15 46 19](https://cloud.githubusercontent.com/assets/22787581/19301724/6f2bbf26-9093-11e6-87c4-2aae942fd552.png)
(https://cloud.githubusercontent.com/assets/22787581/19301687/4f25acfa-9093-11e6-9ca1-2ddc0da9a6c6.png)
![screenshot 2016-10-12 15 46 11](https://cloud.githubusercontent.com/assets/22787581/19301689/4f416d46-9093-11e6-828f-cc285212dbbe.png)

![screenshot 2016-10-12 15 50 29](https://cloud.githubusercontent.com/assets/22787581/19301764/a8c96d6e-9093-11e6-88ec-abfa4094c7e1.png)

**Comment by Masuzu** [comment]
Hello,

Could you try again with a different initial hand layout, one for which the card on the left on the board is not a 10 of spades?

**Comment by WildKaiser** [comment]
Woah it worked all of a sudden! Thank you for your quick reply. So there's a bug with the 10?

**Comment by Masuzu** [comment]
Great news!

About the 10 of spades (the other 10 in other suits should work fine), somehow yes it is is a known issue, sorry about this. I will work on it to avoid this kind of issue.

**Comment by Masuzu** [comment]
Hello,

I have some good news for you regarding this issue with the new update 1.8.3!
https://poker-bot.azurewebsites.net/en/Home/PatchNotes

Enjoy

**Comment by WildKaiser** [comment]
Hi there! Just wanted to say great job on the bot. Thank you very much for fixing the issue too
