### ISSUE TITLE
New user expired license

### ISSUE THREAD

**Issue by redux92** [Masuzu/GBFPokerBot#201]
So i find out about this a couple of hours ago and i wanted to give it a try but the serial number i got is already expired. Can i change it somehow? 

PD: this is the serial number d8846b1dd3a052039b7a28a2c6cd3781892e3522700b8041224102af97732decb7842c69b73ddb719998106cfbfcd792fd9dca6841b13cbaca55fe6baa0a2ff1

**Comment by Masuzu** [comment]
Hello,
Unfortunately there are no more free trial periods.
