### ISSUE TITLE
#203 Poker Table Hook Error, Please Help.

### ISSUE THREAD

**Issue by Azarumi** [Masuzu/GBFPokerBot#205]
Before there isn't any problem with the bot but now I can't use them

here is the picture I took that I was set up correctly

https://imgur.com/a/OwyYNIF

Is there anyway to get it fixed ? @Masuzu

**Comment by Azarumi** [comment]
and Now I got error the failed to perform recalibration, is there anyway to fix it

**Comment by Masuzu** [comment]
Hello,
This is a rare issue, but can happen more often depending on your computer specs and latency.
Increasing the values of GameLatencyCompensationInMs and ConsecutiveFramesWithoutMovement in the configuration file GBFPokerBot.ini is recommended for higher latencies and computer specs on the lower end.

**Comment by Azarumi** [comment]
Thanks for the respond,
I'll try and will update to you today, was being busy with stuffs.

**Comment by Azarumi** [comment]
https://imgur.com/a/bJlnqq6

here is the result of fixing like you said. 

- mouse pointer never move even you're starting the bot
- after running a few selection on poker card, it always say error " failed to perform recalibration "

What can I do after this ? or maybe should I send you email for the faster way.

**Comment by Masuzu** [comment]
There is no need to have such a large browse size and as a side effect it can lead to more recalibrations when it should not (assuming the parameters under the `MotionCapture` section of your .ini file are configured properly for _your_ computer specs).
A browser window as shown below is enough:
![image](https://user-images.githubusercontent.com/5464705/42138163-24fce2c0-7d79-11e8-871d-9f18906dfeea.png)
is enough
