### ISSUE TITLE
License issues when trying to run bot on a different PC

### ISSUE THREAD

**Issue by arjan127** [Masuzu/GBFPokerBot#208]
Basically, see title. I've tried to run the bot on a different PC than the one I bought/tested it on; just so I could use that PC for other things. Important to note that I'm not trying to run them at the same time, if that's a restriction to begin with. It keeps telling me that there's an issue initializing the serial, while the one generated by the generator and the one I set on my account are definitely the same. 

What I can tell you as well is that if I try running it on my initial PC again, it works fine (after I change the serial code back to what it was).

Please advise.

**Comment by Masuzu** [comment]
Hello,
Please use the contents of the serial_number.txt generated when the bot starts, which can sometimes be different from the one generated by the serial number generator. As for why, unfortunately it is too rare of an occurrence to be worth investigating.
