### ISSUE TITLE
unregisterd user

### ISSUE THREAD

**Issue by valentina111** [Masuzu/GBFPokerBot#21]
Hi Masuzu
I still cannot use. After new version & i changed my serial number. 
[Imgur](http://i.imgur.com/2Sa5N3f.jpg)
 my email : naynha______@gmail.com

**Comment by Masuzu** [comment]
Hello @valentina111 ,

Could you please send me your serial number and key.txt file at gbfpokerbot@gmail.com?

Thank you

**Comment by valentina111** [comment]
serial: 5909af0777e361ee6712db7c73a2b91689465de5f257b829ad318274f4fca92c221ebc59296ff20b65258553e7bc0e9459f249c068b70ad7f99370ccda6593f9
key.txt: j5yE31u3GRUj5rrJE4mJxRAq8Fzgskn0KZDbrOOGevxTFYIIrCXKKTIUDQrALldPgvFfq32Q66RM5dogQivXBccG3uXLGbDHkF8kWYAQIzU=

**Comment by valentina111** [comment]
Send <3

**Comment by valentina111** [comment]
i have done with it =)) its ok, tks
