### ISSUE TITLE
OpenCV Error when launching for the 2nd time

### ISSUE THREAD

**Issue by earthlemon** [Masuzu/GBFPokerBot#213]
Hi there.
My Poker Bot was running smoothly and everything on my 1st time run.
But when I tried to start the bot the 2nd time the same way I started my 1st time,  I started receiving this error and can no longer run the bot. 
I have checked around for solutions from people having the same problem as mine on "Issues" and tried their method to fix it. But I can't seems to get it to work

P/S: Got the bot working now after I deleted and re-downloaded the bot.

![error](https://user-images.githubusercontent.com/49832975/56468687-46dd6d80-6462-11e9-95a0-a8bba25f6f60.png)

**Comment by earthlemon** [comment]
It's okay now. I deleted and re-download the Poker Bot and managed to get it working again.

**Comment by earthlemon** [comment]
Tried my 3rd time to run it and it's back again.

**Comment by earthlemon** [comment]
@Masuzu 

I have been trying to fix the error problem on my own.... But I just can't seems to get the bot to work even though I've followed everything from the instruction. Please help me with fixing this issue and get the bot to work, thanks...

![Masuzu1](https://user-images.githubusercontent.com/49832975/56597534-47723180-6625-11e9-88b4-76cb8fe61559.png)
![Masuzu2](https://user-images.githubusercontent.com/49832975/56597535-480ac800-6625-11e9-9e5a-41c9ca94ab26.png)
![Masuzu3](https://user-images.githubusercontent.com/49832975/56597537-480ac800-6625-11e9-8b32-68ce334d69ac.png)
![Masuzu4](https://user-images.githubusercontent.com/49832975/56597538-48a35e80-6625-11e9-83e1-d8b4088a1cac.png)
![Masuzu5](https://user-images.githubusercontent.com/49832975/56597539-48a35e80-6625-11e9-8d7c-f08f02c78ae7.png)

**Comment by Masuzu** [comment]
Hello,
This error message typically indicates that you forgot to decompress the downloaded archive!
