### ISSUE TITLE
charged wrongly

### ISSUE THREAD

**Issue by NatKiasu** [Masuzu/GBFPokerBot#218]
for some reason, when i tried to buy license for pokerbot they charged me for sarasa bot instead. please give a refund or change the license as needed as I do not need sarasabot

**Comment by NatKiasu** [comment]
Um, hello? I really want to get the poker bot but I can't afford both that and the sarasabot I never wanted...

**Comment by Masuzu** [comment]
Hi,
Please request the refund through PayPal.
