### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by Lixow** [Masuzu/GBFPokerBot#22]
Having problems downloading from the page. clicking the button, leads me to an oops something went wrong.
![oops](https://cloud.githubusercontent.com/assets/9908363/19372399/b2547ada-9189-11e6-883f-582708382060.PNG)

**Comment by willow22** [comment]
same

**Comment by Masuzu** [comment]
Hello @Lixow and @willow22  and anyone who might also run into this issue. 
Ooopsies, this one is on me.
I am really sorry for the trouble and will fix this in 10 hours from now.

I will keep you posted.

**Comment by Masuzu** [comment]
It has been fixed.
