### ISSUE TITLE
Can't download a poker-bot Q - Q

### ISSUE THREAD

**Issue by Seiryuha** [Masuzu/GBFPokerBot#23]
![sdsdsd](https://cloud.githubusercontent.com/assets/22828242/19373620/9e1a601e-91ef-11e6-887b-fce1e2047bae.png)

**Comment by Masuzu** [comment]
Hello @Seiryuha and anyone who might also run into this issue. 
Ooopsies, this one is on me.
I am really sorry for the trouble and will fix this in 10 hours from now.

I will keep you posted.

**Comment by Masuzu** [comment]
It has been fixed.
