### ISSUE TITLE
failed to detect position of cards

### ISSUE THREAD

**Issue by dchoo0004** [Masuzu/GBFPokerBot#24]
All settings are correct, and everything worked a few hours ago with no changes made.
![untitled](https://cloud.githubusercontent.com/assets/22593048/19407835/cf7d5e18-927b-11e6-84e7-613aef1ccc05.png)

**Comment by Masuzu** [comment]
It looks like the 10 of spades on the left side is still causing issues.
Just launch the bot on a different hand configuration.
