### ISSUE TITLE
i got to verify a capcha.

### ISSUE THREAD

**Issue by po456asd** [Masuzu/GBFPokerBot#25]
idk how to say in english. i think it a bot check system that i should tell you.

![image](https://cloud.githubusercontent.com/assets/13596788/19423078/cf2539dc-9446-11e6-8e3d-b50347142c9f.png)

**Comment by po456asd** [comment]
Nah. Got banned now.

**Comment by Masuzu** [comment]
Hello,

You will get a captcha after playing for 5 hours or so. The bot will stop after a few seconds when this happens.
Staying online for an abnormally long time, with the poker window active and with someone or bot playing is highly  discouraged. No regular human being would play for such extended period of times. I have been fine for 2 months now. Please just do not be too greedy.
I will consider adding some random long-duration pause for the bot, for instance several minutes where it won't do anything, and more control on the random parameters affecting the delay between the bot actions.
This will be my top-priority for the next coming days.﻿

There are also reports saying that people may be banned if they tend to actions before waiting for the turn to process. Regarding this matter, the bot will never "spam" clicks on a button if you have a regular internet connection and a good computer. It will always wait for the turn to process (i.e. card animations finish loading) beforehand. You can check it by setting the Click parameter in the [Debug] section of the GBFPokerBot.ini file to 'true'.﻿

**Comment by po456asd** [comment]
How about 2-3 hr per day or 2-3 hr and pause for some 30 min- 1 hr?

**Comment by Masuzu** [comment]
Yes, something along those lines. The issue is not really about people playing 10 hours a day with frequent breaks, but people playing 10 hours straight.
