### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iDorkyKenny** [Masuzu/GBFPokerBot#27]
![screenshot_6](https://cloud.githubusercontent.com/assets/17240142/19424897/3954cce2-93e2-11e6-979c-556d1cdbd002.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/17240142/19424899/3a6a55c0-93e2-11e6-9923-fda2ac64e813.png)
the first 5 characters of my number is: 485b1

**Comment by po456asd** [comment]
Change serial in web agains

**Comment by iDorkyKenny** [comment]
how to check my serial?

**Comment by iDorkyKenny** [comment]
how to change my serial? it just shows up the same one

**Comment by po456asd** [comment]
Try Reinstall key.text in bot folder

**Comment by po456asd** [comment]
Don't change anything in that file.

**Comment by Masuzu** [comment]
Hello,

Please go to https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber to change your serial number. Make sure the serial number displayed matches the one generated by the serial number generator.

**Comment by iDorkyKenny** [comment]
it does matches but still doesnt work :(

**Comment by iDorkyKenny** [comment]
i fixed it by changing the compatibility mode to windows 7
