### ISSUE TITLE
Double up with 3 heart always bugged

### ISSUE THREAD

**Issue by luziferx360** [Masuzu/GBFPokerBot#3]
SS 

http://imgur.com/a/I6RJe

It's bugged everytime I pull double up with 3 heart 
only with 3 heart I guess

thx

**Comment by Masuzu** [comment]
Hi,

I will fix this within 24 hours.
The detection threshold of 0.75 might be a bit too harsh in this case.

**Comment by Masuzu** [comment]
The version 1.7.2 should solve this issue:
https://poker-bot.azurewebsites.net/en/Home/PatchNotes

By the way, it is better to have a non maximized browser window to avoid such issues:
Browser screen setup to avoid:
https://s22.postimg.org/i3kjexjld/To_avoid.png

Preferred browser screen setup:
https://s22.postimg.org/583olas4h/Preferred.png

(those screenshots are not scaled up or scaled down).

**Comment by Masuzu** [comment]
The version 1.7.2 introduced a bug in which the bot will try to perform its recalibration after the first desynchronization during the card value detection phase. This recalibration is expected to occur after the eighth consecutive such desynchronization. The version 1.7.3 will fix this issue and will also support different browser window sizes (the only supported window size supported for now is the medium one, see http://game.granbluefantasy.jp/#setting/pc).
