### ISSUE TITLE
How to Activate License

### ISSUE THREAD

**Issue by cielatelier** [Masuzu/GBFPokerBot#30]
this is my first time here in github so I apologize if there things that I got wrong in it.

I did like what you did so I decided to support you for it.

but this shows up after downloading it again.
![gbf bot](https://cloud.githubusercontent.com/assets/23025028/19637234/8c4e9fd0-9a00-11e6-8712-14c98e7082df.PNG)

Clicking the "get a License" will direct me to this 
![gbf bot 2](https://cloud.githubusercontent.com/assets/23025028/19637254/adec3f76-9a00-11e6-866a-0cbe7d248dd9.PNG)

if you will ask if I did activate my license?
![gbf bot 4](https://cloud.githubusercontent.com/assets/23025028/19637305/e7c670e0-9a00-11e6-8ee1-24b3014f3bc0.PNG)

**Comment by cielatelier** [comment]
nevermind... so you need to change serial number.. sorry for your time silly me

**Comment by cielatelier** [comment]
Can we only use 1 PC per license?

**Comment by Masuzu** [comment]
Hello,

I am glad you could figure it out and for reporting the issue with the dead link. I will fix it in a few hours from now and I apologize for the trouble it caused.
Yes that is right, the licence is bound to a single PC. However, should you use another computer, you can still re-use the same licence.
To do so, you will need to get a new serial number for this computer (running the [serial number generator](https://poker-bot.azurewebsites.net/en/Account/GBFPokerBotSerialNumberGenerator) and update the serial number on the management page https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber
