### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by Seraa** [Masuzu/GBFPokerBot#31]
Hello, I had disconnection issues when I was using and later was banned when I was using the program. I want to make sure the bot is undetectable so could you give me a 36 hour trial? I will only run it for 2 hours a day to make sure it is undetectable. my serial number starts with 98533

thanks

**Comment by Masuzu** [comment]
Hello,

The trial period countdown starts from the moment you register, meaning you can't run in for 2 hours a day for multiple days without getting a licence.
Trial extension period are exceptional and I will see what I can do for you.

Cheers

**Comment by Seraa** [comment]
Thank you, I was wanting to see if I had problems or bans again before I buy.
