### ISSUE TITLE
Version isn't updated no matter what

### ISSUE THREAD

**Issue by Fujiwario** [Masuzu/GBFPokerBot#32]
When I click download pokerbot from the account page, it only shells out V1.8.3 instead of 1.9.4 and as a result, I can't try out the bot.

![ss 2016-10-28 at 02 43 53](https://cloud.githubusercontent.com/assets/23118118/19802461/b12d648e-9cb8-11e6-93ef-5e56f28aa8c4.png)

**Comment by Masuzu** [comment]
Hello,
GBFPokerBot.exe is the current version.
