### ISSUE TITLE
Banned part 2

### ISSUE THREAD

**Issue by Seraa** [Masuzu/GBFPokerBot#33]
Hello, I have waited patiently for few days and no reply. I have money ready but how can I trust program that has disconnection issues and banned for parts of the trial.

Thanks

**Comment by Masuzu** [comment]
Hello,

You registered on October the 24 and issued your extension query 3 days later. I am sorry but I can't comply with such requests.
Disconnections issues is under your own responsibility and your ISP.

Regards
