### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by Sudoandu101** [Masuzu/GBFPokerBot#34]
![1](https://cloud.githubusercontent.com/assets/23221691/19943958/1986c966-a110-11e6-917f-ba7a52e21981.PNG)
![2](https://cloud.githubusercontent.com/assets/23221691/19943959/1987b9a2-a110-11e6-992f-34abdfd3f336.PNG)
![3](https://cloud.githubusercontent.com/assets/23221691/19943960/199cd4e0-a110-11e6-851d-f5732fd4775d.png)

The first and second picture is my setting in game and the third picture is my issue. 
Please help me!
Thanks.

**Comment by Masuzu** [comment]
Hello,

The 'High' resolution setting is not tested and is not supposed to work properly as far as I can remember.
Also, is the picture you sent resized? You cards seem to be a bit too large for a "Medium" Window size, probably another scaling issue (you may want to check http://www.pcworld.com/article/2953978/displays/use-windows-10s-individual-display-scaling-to-perfect-your-multi-monitor-setup.html and https://poker-bot.azurewebsites.net/en/Home/Requirements).

**Comment by Sudoandu101** [comment]
Hello,
The problem has been solved. My screen scaling was 125% which made everything went wrong. The software now work perfectly for me. Just an update for your information, it works pretty well with the "High" resolution setting.
Keep up the good work,
Thank you!

**Comment by Masuzu** [comment]
Awesome, I am glad you could figure out the issue.
