### ISSUE TITLE
Stat windows show wrong information

### ISSUE THREAD

**Issue by zephythor** [Masuzu/GBFPokerBot#35]
It's show winning chips at lose chips and bot did not update how many chip is spent. Information in attached picture.

![ca1](https://cloud.githubusercontent.com/assets/1861588/19944538/f285662e-a16e-11e6-93b4-9d4a2961af44.png)

BTW, Could you please make this status write to a log file when bot is shutting down? It would be nice.

**Comment by Masuzu** [comment]
Hello,

Indeed this was an issue which has just been fixed with the version 1.10.2: https://poker-bot.azurewebsites.net/en/Home/PatchNotes
