### ISSUE TITLE
desynchronization

### ISSUE THREAD

**Issue by maso94** [Masuzu/GBFPokerBot#36]
![desync](https://cloud.githubusercontent.com/assets/22984523/19988052/8031f3b6-a21e-11e6-8575-7e011fc83dec.PNG)
sometimes this happens, what should i do?
it keeps going on i have to stop the bot...

**Comment by Masuzu** [comment]
Hi,

I will look into it. Could you send me the PokerBotTableHook.png file along with this screenshot if you still have and/or if you run into the same issue again?

**Comment by Masuzu** [comment]
Now I think about this, make sure you do not use the *High resolution* setting on the [setting](http://game.granbluefantasy.jp/#setting/graphics) but the *Standard resolution*.

**Comment by Masuzu** [comment]
Some changes have just been made to improve the card detection. The patch notes can be found [here](https://poker-bot.azurewebsites.net/en/Home/PatchNotes)
Please feel free to reopen the ticket if you run into other issues.

Cheers

**Comment by maso94** [comment]
sry if i am late but i just tried the new version
if before the desynchronization happened sometimes now happens everytime...
here is the screenshot

2016-11-04 22:41 GMT+01:00 Masuzu <notifications@github.com>:

**Comment by maso94** [comment]
i forgot to add
i setted everything as stated in your guide and in the trial period it
didn't give any sort of problems

2016-11-05 20:04 GMT+01:00 luca masotto <madarame94@gmail.com>:
