### ISSUE TITLE
missing msvcp120.dll and msvcr120.dll

### ISSUE THREAD

**Issue by blasterion** [Masuzu/GBFPokerBot#37]
I downloaded them and put them in the folder but now i get another error 0xc000007b

**Comment by Masuzu** [comment]
Hello,
You can't do it this way. You need to install VC++ 2013 Redistributable package for 32 bits, which you can get from here: https://www.microsoft.com/en-us/download/details.aspx?id=40784
Make sure to download the 32 bit version (vcredist_x86.exe)

You may want to check https://poker-bot.azurewebsites.net/en/Home/QuickStart
