### ISSUE TITLE
Cant get the licensed version to work (just repurchased). Changed serial number and now stuck still not working with 4 days cant use

### ISSUE THREAD

**Issue by evad83** [Masuzu/GBFPokerBot#38]
Hi,

After repurchase, i ran the old serial number generator since running the new pokerbot keep showing my version to be unlicensed. I then changed the serial number to that. Still no luck
I then noticed the generator included in the new version and ran that (another new set of code). I cant change my serial number again though (4 days cooldown)

Is there anyway for help in reset on this cooldown as this is frustrating as I had just repurchased and want to use it.
I dont know why the serial number keep having problems.
Only possibility is I am using VPN for some other games that I played when I was using (assuming the generated codes are affected by the IP address)

Please kindly assist.
Thank you.

**Comment by Masuzu** [comment]
Hello,

Could you please send me your *updated* serial number and the email address used to register at gbfpokerbot@gmail.com?
I will override the existing serial number causing the issue in a few hours from now and let you know when it is done.

Best regards

**Comment by evad83** [comment]
Hi,

My email address is d2103@hotmail.com
Using the key generator that I just ran right now (running from the latest version of the game 1.10.3), below is the code:
07fcd86ad1b635c93211c4f2f8bd01b1b6c473b074bc0258e70764b516df0db1910b3bfba84deafb471d45f5d20c747b38ab2ff853c47e0332e1c1b9bec4380b

Please let me know if any more info is needed.
Thank you.

Best Regards

**Comment by Masuzu** [comment]
Hi,

Thank you for the information, much appreciated :) I will make the changes in a few hours from now.
I removed the information for privacy concerns.

Cheers

**Comment by evad83** [comment]
Hi,

Thanks. I should have sent pm directly.
I'll wait for your update then.

**Comment by Masuzu** [comment]
Hello, the update should be effective now.
Let me know if you still have issues.

**Comment by evad83** [comment]
Hi, 

Sorry for the late reply.
Just wanted to update that all is working fine
Thanks
