### ISSUE TITLE
OpenCV error

### ISSUE THREAD

**Issue by dchoo0004** [Masuzu/GBFPokerBot#4]
when running, right after the "licens expires in xx hrs" window, I get a command line error:

OpenCV Error: Assertion failed (s>=0) in cv::setSize, file C:\builds.... matrix.cpp, line 116

**Comment by dchoo0004** [comment]
Nevermind, I had the game settings wrong, seems to be working now.

**Comment by Masuzu** [comment]
Yes, scaling issues are most of the time the cause of such issues.
