### ISSUE TITLE
after 1.11.4 update i can't use bot anymore

### ISSUE THREAD

**Issue by po456asd** [Masuzu/GBFPokerBot#40]
![virtualbox_poker_05_11_2016_22_33_32](https://cloud.githubusercontent.com/assets/13596788/20031327/37954b04-a3a8-11e6-8fee-666cf1999d3b.png)

surely no one hold and move the mouse.

**Comment by po456asd** [comment]
update. i tried downgrade to 1.10.3 and it worked fine.

**Comment by Masuzu** [comment]
Hello,

That is quite weird indeed, I can't reproduce this issue.
In any case, I am now working on a completely different approach using neural network to identify the card values, which bypasses a lot of the current issues. So far it is working wonders :) The integration with the existing bot may take some more time though.

**Comment by s4535065** [comment]
It seem like I have the same issue here. It can work for a few turn then it desync and cannot re calibrate. 
![desync issue](https://cloud.githubusercontent.com/assets/23288439/20035419/7cc65f10-a416-11e6-97fd-24f7e8637180.PNG)

**Comment by Masuzu** [comment]
That is quite weird indeed since on my side the recalibration was alwasy the successful. My guess is that the correct card value is found but is just below the detection threshold.
For instance, in the picture from @s4535065 , the misdetected 4th card is probably the correct one (5c) but with a score slightly below the threshold. The slightly modified version 1.11.4b now life will display the most likely card being matched.
If that's the case, the treshold would need to be adjustable.

**Comment by po456asd** [comment]
much thanks :) now 1.11.4b worked fine

**Comment by Masuzu** [comment]
I am glad to hear so!

**Comment by maso94** [comment]
![desync 3](https://cloud.githubusercontent.com/assets/22984523/20036662/8aca176c-a40e-11e6-8a4f-de99d6e61a8c.PNG)
even with the new version it goes like this...

**Comment by ssuperkid5** [comment]
Make sure your animation settings are the ones on requirements page (i.e. make sure it's set to beta) I kept getting these errors as well and I checked that. Additionally, when it was around the time that the captcha was going to appear, it started to glitch as well.

**Comment by Masuzu** [comment]
Hello guys,
Ah got it, the threshold is a bit too harsh.
I will fix it right now.

**Comment by maso94** [comment]
the settings are setted as shown in the requirements page

**Comment by po456asd** [comment]
updateee. it be like this now need to restart program to make it work again.

1.11.4b


![virtualbox_poker_06_11_2016_18_13_52](https://cloud.githubusercontent.com/assets/13596788/20037128/ed0288ea-a44c-11e6-978c-9cf279d7f71d.png)

**Comment by Masuzu** [comment]
By the way, could it be that you are using High resolution settings on your http://game.granbluefantasy.jp/#setting/graphics menu?
The detection threshold has been slightly lowered in the version 1.12.0.

**Comment by maso94** [comment]
i am using the standard one

**Comment by po456asd** [comment]
here it is 
![image](https://cloud.githubusercontent.com/assets/13596788/20037226/44cea62a-a44e-11e6-9bb5-4743405e94d7.png)

**Comment by Masuzu** [comment]
Ok, got it, thank you.
This is there a blatant proof as to why machine learning for image processing killed computer vision ^^
Joke aside, I am still working on revamping the detection system.

**Comment by po456asd** [comment]
Keep up the good work! 👍

**Comment by maso94** [comment]
![settings](https://cloud.githubusercontent.com/assets/22984523/20037261/a6a88ce4-a41c-11e6-9fd8-72ac32485db9.PNG)
here is my settings

**Comment by po456asd** [comment]
@Masuzu some feature i like to see is auto pause botting like after 2hr of botting the bot automatically pause, show static by itself and need user to press start to make it botting again (disable by default)

**Comment by Masuzu** [comment]
@po456asd Sure, I can do that. This will be done by tomorrow.

**Comment by Masuzu** [comment]
@po456asd now done in version 1.13.0.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes

**Comment by po456asd** [comment]
@Masuzu heya i just thinking i want a feature that play "sound" when desync so owner can know it  just desync or get a captcha.
