### ISSUE TITLE
Bought license, not letting me use

### ISSUE THREAD

**Issue by snowy1230** [Masuzu/GBFPokerBot#41]
I bought the extension of the license and the bot's not letting me run it.

![image](https://cloud.githubusercontent.com/assets/23285050/20033914/1866591e-a36a-11e6-8394-fbd231d175a7.png)

**Comment by Masuzu** [comment]
Hello,

Please make sure that the licence number generated by the serial number generator matches the one on this page:
https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber

**Comment by snowy1230** [comment]
I thought that was the case so I tried copy + pasting the code from the serial generator but it said the code's already been taken, so I randomly changed a number and it won't let me change again for 4 days.

Could you help me with setting my code to my account somehow? I don't want to waste 4 days of the monthly license. Thanks for the quick response.

**Comment by Masuzu** [comment]
The serial number code is unique per computer. If it is already used, then someone must have already taken it already.
I can try to check it if you send me by mail at gbfpokerbot@gmail.com the email address you used to register as well as the serial number you are trying to input.

**Comment by Masuzu** [comment]
Mailed and fixed.
