### ISSUE TITLE
Licence expired

### ISSUE THREAD

**Issue by landax** [Masuzu/GBFPokerBot#44]
Hi, I just renewed the key for 1 month (just paid) but when I turned on the bot it says Granblue Fantasy poker bot Licence expired. Is it because I was using the bot on different computer? I tried to change the serial number but doesn't work

**Comment by Masuzu** [comment]
Hello,
Indeed, you can't use the same licence on 2 different computers.
To do so, you need to regenerate a serial code for the other computer you want to use and update it here: https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber
Please keep in mind that it is only possible to change the serial number once every 4 days.
