### ISSUE TITLE
i keep geting the unregisered user message

### ISSUE THREAD

**Issue by zx192** [Masuzu/GBFPokerBot#45]
I have downloaded and updated the poker bot but it still gives me the same message.  i have tried changing the serial number but i keep getting the following message.

Name c28239ac52ca6ed57d39ac0eab953d1c927955f3b50080a9fbf154ad67eae0961202a8312f8740b6f3c634c1c684a10ae7dc1ee6d2c2b66f13f5adc580c476e4 is already taken.   
 I have used the poker bot using two different computers and accounts and the account i bought the license for was for the alternative computer which i cannot use at the moment and may be the reason for the serial number issue.

my email is ligerzerox1@gmail.com plz contact me asap

**Comment by Masuzu** [comment]
Hello,
Indeed, you can't use the same licence on 2 different computers.
To do so, you need to regenerate a serial code for the other computer you want to use and update it here: https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber
Please keep in mind that it is only possible to change the serial number _once every 4 days._

**Comment by zx192** [comment]
what part of i have tried changing my serial number and got the following error message :8ball:  

c28239ac52ca6ed57d39ac0eab953d1c927955f3b50080a9fbf154ad67eae0961202a8312f8740b6f3c634c1c684a10ae7dc1ee6d2c2b66f13f5adc580c476e4 is already taken.

did you not under stand this is the serial number that gets generated for the computer every time so could you please reset it or send me a new one that works via email
