### ISSUE TITLE
version 2.0 always desync on 10d card

### ISSUE THREAD

**Issue by zey71** [Masuzu/GBFPokerBot#47]
version 2.0 always desync on 10d card (It's always detected that card as 7d) details in picture.
![fail](https://cloud.githubusercontent.com/assets/1861588/20231384/f220f51e-a893-11e6-905b-ec88a3f4bad4.png)

**Comment by Masuzu** [comment]
Hi,
It looks like you are using the non-CUDA version with the old dectection system, as the new version does not check for desynchronizations. Either way, both will have issues if the positions of the 2 cards failed to be detected properly.
Could you please post a screenshot of your `PokerTableHook_2.png` picture which led to this situation?
If this looks like something like this: https://s18.postimg.org/rrj758ucp/Poker_Table_Hook_2.png, I find it hard to believe that 10 could be mistaken with a 7 but I will check later on.

**Comment by cnzqy1** [comment]
Same issue here. I attached the picture.
![pokertablehook_2](https://cloud.githubusercontent.com/assets/8440715/20243089/f155d46a-a915-11e6-9a23-bc8ae10dcdf2.png)

**Comment by Masuzu** [comment]
Ok got it.
I will make the detection thesholds parameterizable so you can lower it from the default 0.85 value if needed. The new version should be released by Monday.

**Comment by zey71** [comment]
Thanks for the fix. BTW I've moved to cuda version and there's no problem until now.

**Comment by Masuzu** [comment]
Sorry for the delay. The fix for the non-CUDA versions has just been released: https://poker-bot.azurewebsites.net/en/Home/PatchNotes
Happy hunting
