### ISSUE TITLE
App closes after launching

### ISSUE THREAD

**Issue by Tagrim36** [Masuzu/GBFPokerBot#48]
I reinstalled OS to windows 8 (from 7), download new version of BOT (CUDA) and key file. But when i tried to launch application, it closes after click on "OK" button. 
_User email: jas******@yandex.ru_

![1](https://cloud.githubusercontent.com/assets/23420289/20239100/45572fba-a901-11e6-9a01-4317e307f6b3.png)

**Comment by Masuzu** [comment]
You may need to reinstall your NVIDIA drivers. Not having those installed will most likely result in this error.
If this is still not enough, then you should also install CUDA Toolkit 8.0: https://developer.nvidia.com/cuda-downloads

**Comment by SarahCSharp** [comment]
I have the same issue with it closing after opening even after downloading the CUDA Toolkit 8.0. The older version doesn't seem to work either because when you launch it, it tells you that there's a new version and when you close that message it just closes the whole thing.

**Comment by Masuzu** [comment]
What older version are you downloading? The 64-bit client from this page https://poker-bot.azurewebsites.net/en/Manage should be version 2.0.0 and should not even display version info window.

**Comment by Tagrim36** [comment]
Bot close without any error. May be something wrong with key file? (I download it from site, with latest version of application).

**Comment by cnzqy1** [comment]
I have the exact same issue with the CUDA version. No error from the bot either.

**Comment by Masuzu** [comment]
If it closes without an error, then my guess is that just running the GBFPokerBotSerialNumber.exe file should not work either.

**Comment by cnzqy1** [comment]
The non-CUDA version works just fine (except for the 10d detection issue which I reported in the other thread).

Installing MS-MPI still doesn't solve the problem. The program closes after clicking the "OK" button before it shows the license expiration time window. It is also not my firewall blocking the bot. I have a GTX 1070 with Compute Capability 6.1 so it shouldn't be a problem either.

**Comment by Masuzu** [comment]
@cnzqy1 :thinking: Thank you for the feedback. I will try to investigate the missing dependency issue for  the CUDA version on a "virgin" computer. It looks like for some people it is working fine, as reported by zey71 for instance.

**Comment by cnzqy1** [comment]
A little more information: I downloaded 1.13.1_x64 again to have another test, and this time I realized that there was an error (the screen closed so fast that I barely saw it). Here is the screenshot:

![untitled](https://cloud.githubusercontent.com/assets/8440715/20282577/59874b68-aa83-11e6-817e-5894026b1510.png)

I tried unblocking the key.txt file after I downloaded it but still the same error. On the other hand, the 2.1.0 CUDA still won't run (couldn't see any error). The non-CUDA 2.1.0_x64 works fine.

One thing in common is that for both versions that won't run I'm required to put in the key.txt file manually, although I'm not sure how this is related.

**Comment by Masuzu** [comment]
Hello,

You are using a GTX 1070 which uses the new "Pascal GPU" architecture. The current GBF poker bot CUDA version uses CUDA 7.5 which unfortunately won't work with Pascal GPUs.
To solve this issue, a second version of the bot needs to be recompiled using CUDA 8.0. This will probably take some time but I will work on this to support the new GeForce 10 series.

As for the "Failed to initialize security" error, I am not sure exactly what the reason could be but it should not prevent the bot from running as I encountered it consistently on another Windows 7 laptop I used during tests.

**Comment by Masuzu** [comment]
Good news, new poker bot version using CUDA 8.0 instead of CUDA 7.5 to be released by this Sunday.

**Comment by Tagrim36** [comment]
My problem was solved after changing serial number.

**Comment by Masuzu** [comment]
Hello,

The new version labeled as 2.2.0_x64_CUDA now uses CUDA 8.0 instead of CUDA 7.5.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
https://poker-bot.azurewebsites.net/en/Manage/DownloadGBFPokerBotCUDA
I do not have a GeForce GTX 10 Series at hand so feel free to reopen the ticket should you still have some issues with it.
