### ISSUE TITLE
Cannot change serial number

### ISSUE THREAD

**Issue by landax** [Masuzu/GBFPokerBot#49]
Hi, I wanted to change the bot program to new computer. So it's already 4 days and I tried to change the serial number but this thing occured. Email: landax_lord@hotmail.com
![untitled](https://cloud.githubusercontent.com/assets/23378140/20245241/118b6610-a9d8-11e6-8c3b-d0cee29b81db.png)

**Comment by Masuzu** [comment]
Hello,
I will look into it. It looks like it is a bug.

**Comment by Masuzu** [comment]
This should be fixed now.
Please let me know if there is still and issue by reopening this ticket if needed.
