### ISSUE TITLE
Random crashing during double up

### ISSUE THREAD

**Issue by boxednoodles** [Masuzu/GBFPokerBot#5]
During double up if I'm a few rounds in the program will hang briefly and crash immediately. It doesn't crash immediately during double up, it'll always be a few rounds in and then just dies. Not sure if it's related to the calibration issue in the other thread. 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	GBFPokerBot.exe
  Application Version:	0.0.0.0
  Application Timestamp:	57f29d1e
  Fault Module Name:	MSVCR120.dll
  Fault Module Version:	12.0.21005.1
  Fault Module Timestamp:	524f7ce6
  Exception Code:	40000015
  Exception Offset:	000a7676
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	fb2a
  Additional Information 2:	fb2a24e8ba2717ddd5a9c5132e001981
  Additional Information 3:	4a36
  Additional Information 4:	4a369c96b16ba9fbdfcf49cd77c56846

![2016-10-03 13_34_56-granblue fantasy](https://cloud.githubusercontent.com/assets/22602580/19053281/084d4e6c-896f-11e6-9e4a-ab68cca90b95.png)

**Comment by Masuzu** [comment]
Hello,

Did you encounter the same issue with the previous version (1.7.11)? With the previous version, the bot would have looped indefinitely in this case. The bug you are reporting means that the bot failed to identify properly the position of the 1st card on the board. I am aware that when that card is a 10 of clubs there might be some issues but it should be very rare.

[Browser screen setup to avoid](https://s13.postimg.org/5duvh2vuv/To_avoid.png)

[Preferred browser screen setup](https://s22.postimg.org/583olas4h/Preferred.png)

Using the preferred browser screen setup showcased above, we can somehow avoid such issues.
I will look thoroughly into this matter in the next days.

**Comment by boxednoodles** [comment]
The version I'm using is v.17.2. This is my browser screen. It should be optimal enough for the poker bot to run. I'll kill the submenu and tighten the window further and see. 

![2016-10-03 14_24_35-granblue fantasy](https://cloud.githubusercontent.com/assets/22602580/19054698/5f2b958a-8975-11e6-8137-20e4ccb34196.png)

**Comment by Masuzu** [comment]
Indeed, it would be great if you could upload your Poker_Table_Hook.png picture please.

**Comment by boxednoodles** [comment]
![pokertablehook](https://cloud.githubusercontent.com/assets/22602580/19054829/f60c0dae-8975-11e6-8933-b8b9092cac8d.png)

**Comment by Masuzu** [comment]
Ahhh!!! Got it!
As you can see, the hook system occurred too soon: the right card was still loading.
This issue happens with low-end computers which can't take enough screenshot per second to detect the end of the animations. A solution in this case it to play with the values in the section [MotionCapture] of the ini file.
```
ConsecutiveFramesWithoutMovement=30 -> might need to be decreased for your computer
MinDelayInMsBetweenFrames=5 -> might need to be decreased for your computer
```

**Comment by boxednoodles** [comment]
I see. I'll lower the values and leave the bot running for a while and wait.

**Comment by Masuzu** [comment]
As soon as you reach the higher or lower phase, you can press escape to stop the bot and check that your Poker_Table_Hook.png picture look like this: https://s4.postimg.org/jnvf137ct/Poker_Table_Hook.png

As long as it is not the case you will run into those crashes.

However, after you manage to tweak your ini settings to have the expected Poker_Table_Hook.png, if you still run into crashes, please let me know.

**Comment by Masuzu** [comment]
Just a correction to my previous comment in case you did not notice it:
```
ConsecutiveFramesWithoutMovement=30 -> might need to be **increased** for your computer
```

**Comment by boxednoodles** [comment]
I'm still getting the same errors, the only difference is how late I can delay when this happens. I can get a few winning hands before the program stalls and crashes like in the first screenshot. During some value tweaking there are times where I'll get at quite a few desynchronization to one of the buttons. Sometimes it's Yes, sometimes it's Low or High button. 

This is the current PokerTableHook
![pokertablehook](https://cloud.githubusercontent.com/assets/22602580/19057397/685562e4-8984-11e6-925f-eb24cfe0628f.png)

**Comment by connectve** [comment]
I've got the same issue and I tried the fixes listed here, my pokertable hook looks appropriate as well, yet the same error as the one above appears on the first double up it gets without even getting through a round. 
http://puu.sh/rx4wX/7eba695996.png Or this popup appears
![pokertablehook](https://cloud.githubusercontent.com/assets/22608057/19062276/a6128106-89c6-11e6-9e68-09a24c6b1559.png)

**Comment by Masuzu** [comment]
If it can't through a round and crashes, the console should display the message "Perform recalibration", is that correct?

**Comment by boxednoodles** [comment]
All the errors I get all start with OpecnCV Error: Assertion failed. The one other time I got an error a pop up appeared saying "Double up chance expected to find 2 cards." during the first round of the double up. 

This is the latest screenshot

![2016-10-03 19_01_34-granblue fantasy](https://cloud.githubusercontent.com/assets/22602580/19068588/042c448c-89d8-11e6-87a5-d1d24a7a7de8.png)


ConsecutiveFramesWithoutMovement=60
MinDelayInMsBetweenFrames=6

**Comment by Masuzu** [comment]
@boxednoodles It is absolutely impossible to have your error with such an easy card pattern (cards with value 2 are especially easy to detect) unless the hook on the 2 cards occurred too early. Increasing the default 1000 ms before trying to hook on the 2 cards should solve the issue.

**Comment by Masuzu** [comment]
As for the crash during the second round as seen in your last screen shot, you can see that the card detected was a 5 of spades which is obviously wrong. The reason why this happens is that the bot failed to detect the end of the animation (that is to say the moment when the card is card is fully visible on the board) and triggered the card identification too early, therefore detecting a wrong card value instead. On good CPUs this never happens as they are fast enough to detect accurately the end of animations. On the YouTube channel there is still a video showcasing the effect of multiple parameters on the animation detection.
However, I can see that the recalibration kicked in right away, which is a bug indeed. I will fix this tomorrow.

**Comment by Masuzu** [comment]
The version .1.7.3 fixed this annoying bug introduced by the version 1.7.2. I apologise for the inconvenience.

**Comment by Masuzu** [comment]
Hello @boxednoodles and @connectve ,

I am sorry if the advice regarding the update of the GBFPokerBot.ini parameters felt a bit fuzzy.
At last, here is a short self-explanatory video guide showing what I meant and how to get the bot to work smoothly on less powerful computers!
https://youtu.be/vtW7fTDJANk

Best regards
