### ISSUE TITLE
Forgot email

### ISSUE THREAD

**Issue by Greiga** [Masuzu/GBFPokerBot#50]
I forgot the email I used to register, I tried 4 different ones and none of them were sent a password reset code. I have my serial number. What to do?

**Comment by sasha48269** [comment]
I too forgot the email I used to register. I have my serial number. What to do?

**Comment by Masuzu** [comment]
Hello, I will add a password recovery using the serial number by the end of the week.

**Comment by Masuzu** [comment]
Hello,

The email recovery feature is now live:
https://poker-bot.azurewebsites.net/en/Account/ForgotEmail
Please let me know if you run into issues with it.
