### ISSUE TITLE
Granblue Fanatsy Wiki incompatibility

### ISSUE THREAD

**Issue by blasterion** [Masuzu/GBFPokerBot#52]
Ok this one is a bit weird,

I can't have Granblue Fantasy Wiki open and run the bot at the same time apparently the bot thinks it's a separate session of GBF running or something

the website is gbf.wiki/Main_Page

which isn't a problem since I don't really read the wiki while the bot is doing its thing but it's weird

**Comment by Masuzu** [comment]
Got it, I identified the issue, I will fix this issue by the end of the week.

**Comment by Masuzu** [comment]
Hello,

The new version 2.2.0 should have addressed this issue.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
