### ISSUE TITLE
Poker bot CUDA 2.1 report wrong startup time

### ISSUE THREAD

**Issue by zey71** [Masuzu/GBFPokerBot#54]
Poker bot CUDA 2.1 report wrong startup time, Bot will report in someway like -30000 seconds. 
GPU: GTX 1070

**Comment by Masuzu** [comment]
Hello,
What do you mean exactly by "startup time"?

**Comment by Masuzu** [comment]
Ah, you meant the time elapsed from the statistics menu. I will fix this in the next release.

**Comment by Masuzu** [comment]
Hello,

The new version 2.2.0 should have addressed this issue.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
