### ISSUE TITLE
CUDA Version Still Not Working

### ISSUE THREAD

**Issue by cnzqy1** [Masuzu/GBFPokerBot#56]
I tried the 2.2.0 CUDA version on my computer with GTX 1070 and it still closes right after launch. On another computer with GTX 960M the same issue exists. No error message was displayed. The non-CUDA 2.2.0 works fine.

**Comment by Masuzu** [comment]
Hello,

Well, that's quite puzzling. I have no idea what kind of configuration/DLLs you have installed on your side.
At least this other person got an explicit error:
https://github.com/Masuzu/GBFPokerBot/issues/55

**Comment by Masuzu** [comment]
If you are willing to go through this, you could check whether you can run some of the samples for CUDA 8.0 on your machine:
http://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#installing-cuda-development-tools
guides the setup from the installation to launching the samples step by step.

**Comment by dvluong** [comment]
I've done everything recommended and it is still not working for me. Neither the non CUDA or CUDA work. Double click the GBFPokerBot.exe, terminal opens, I see the welcome prompt, and then it just closes.

**Comment by dvluong** [comment]
So this is really weird, I decided to run the GBFPokerBot.exe after opening the zip with winrar instead of extracting it and it runs... I will keep looking into this.

**Comment by Masuzu** [comment]
Hello,

Sorry for the delay, I have been quite busy lately.
I will get back to it as soon as I can.
Sorry for the inconvenience.

**Comment by Masuzu** [comment]
@dvluong As long as you do not change your password on [this](https://poker-bot.azurewebsites.net/en/Manage/ChangePassword) page, there is no need to replace the key.txt file indeed.
Moving the executable file in a different location will very likely cause startup errors due to the fact that  some of the resources are retrieved relatively to the executable file path.

**Comment by dvluong** [comment]
@Masuzu Gotcha, no wonder I had trouble getting it to run. Great piece of software you have here by the way! Keep up the hard work!
