### ISSUE TITLE
Known issue with v2.2

### ISSUE THREAD

**Issue by Masuzu** [Masuzu/GBFPokerBot#57]
The bot won't retry anymore to perform the last action, which helped in some cases when you experienced a lagspike. During higher or lower, this may cause the bot to forfeit with a warning yellow message saying "Wrong card identification" even though the odds are in your favor. Thanksfully this is not a common occurrence but I will fix it.

**Comment by SarahCSharp** [comment]
![image](https://cloud.githubusercontent.com/assets/18587599/20573473/e12d1552-b1ea-11e6-8806-bbff1b4fadbf.png)

Getting this error after getting past the "License expires in x days" part

**Comment by Masuzu** [comment]
Hello,

Sorry for the delay, I have been quite busy lately.
I will get back to it as soon as I can.
Sorry for the inconvenience.

**Comment by Masuzu** [comment]
Busy until the end of year. Enjoy the end-of-year celebrations!

**Comment by Masuzu** [comment]
Dropped due to non-reproducibility/lack of reports of similar cases.
