### ISSUE TITLE
Does this still work with version 1.4.4

### ISSUE THREAD

**Issue by gpo1zeph** [Masuzu/GBFPokerBot#58]
Trying to figure out how to configure Chrome's Granblue app with the suggested settings. So far, I can't get 2 things working:

1. How do you launch the app in fullscreen mode similar to your screenshots and not via the pop-up window Chrome has on default?
2. Where is the Animation/Resolution Settings? Can't seem to find this menu.

Any help would be appreciated. Thanks.

Edit: 

Got it to work. Just discovered that there's actually a browser version of the game. Thought it was only the Chrome app before.

**Comment by Masuzu** [comment]
Hello,

Sorry for the delay, I have been quite busy lately.
I will get back to it as soon as I can.
Sorry for the inconvenience.

**Comment by Masuzu** [comment]
Hello,

1. You want to use the browser version of the game (http://game.granbluefantasy.jp/)
The reason why the Chrome application is not supported is Google plans to [retire Chrome apps](http://www.ghacks.net/2016/08/19/google-to-dump-chrome-apps/) by 2018.
2. You will find the settings on this page http://game.granbluefantasy.jp/#setting after the authentification
