### ISSUE TITLE
Error 0xc000001d

### ISSUE THREAD

**Issue by gpo1zeph** [Masuzu/GBFPokerBot#59]
Can't open the program and having the below error.

http://i.imgur.com/c1LHLA1.png

**Comment by Masuzu** [comment]
Hello,

Sorry for the delay, I have been quite busy lately.
I will get back to it as soon as I can.
Sorry for the inconvenience.

**Comment by Masuzu** [comment]
Does the "licence info" window show up after the greetings window "Brought to you by..."?

This looks like you are missing VC++ 2013 redistributable DLLs, which can be downloaded here https://www.microsoft.com/en-us/download/details.aspx?id=40784
Make sure to choose and download the 64 bit version (vcredist_x64.exe) if you are using the 64-bit version of the client.
Using the 64-bit version on a non-64 Windows OS won't do any good either.
