### ISSUE TITLE
Poker Table

### ISSUE THREAD

**Issue by corncookie** [Masuzu/GBFPokerBot#60]
it seems the poker table mouse click is offset for some reason and i can't click the cards but if i click beside the cards i can click someone ?but if i use another pc/laptop the casino is fine - i don't know what happen lol -   sorry for my bad english and hope you can help me :D -

**Comment by corncookie** [comment]
SOLVE : You just need to reinstall the chrome in order to work it again LOL

**Comment by Masuzu** [comment]
I am glad you could find out on your own the issue!
Good to know for future users who might run into the same problem.
