### ISSUE TITLE
Error 0xc000007b when running serial generator

### ISSUE THREAD

**Issue by hahaer** [Masuzu/GBFPokerBot#62]
Receiving error 0xc000007b when running GBFPokerBotSerialNumberGenerator.exe. I just reformatted my computer to a fresh install of windows 10. Also, I had missing errors for the VC++ 2013 redistributable DLLs (MSVCP120.dll and MSVCR120.dll), which I had installed already. So I copied the DLLs from system32 into the bot folder and this is the resulting error.

https://puu.sh/sFUS8/7388e90048.png

**Comment by Masuzu** [comment]
Hi,

You never want copy these DLLs into your folder, as these DLLs also call internally other DLLs when they are loaded, thus resulting in these errors.
What you want to do usually is installing the correct VC++ 2013 redistributable packages (32 or 64 bit for your computer, from [here](https://www.microsoft.com/en-us/download/details.aspx?id=40784)) and installing the Windows Updates.
Using the 32-bit bot client without the 32 bit version installed or the 64 bit bot client without the 64-bit version also leads to this kind of issue.

**Comment by hahaer** [comment]
Seems like I got around the issue by installing the 32-bit VC++ 2013 redistributable. My machine is 64-bit however and I'm running the 64-bit bot clients.

**Comment by Masuzu** [comment]
Ah, it could be that some of the dependencies which the bot uses are actually compiled to use the VC++ 32-bit redistributable. Thank you for the feedback.

**Comment by hahaer** [comment]
I don't believe I any had errors running the bot. My issue is specifically just with the serial generator. Perhaps you did not compile a 64-bit generator to zip with the 64-bit bot?

**Comment by Masuzu** [comment]
Ah that's right, there is no 64-bit generator, my bad. Nicely spotted :)
