### ISSUE TITLE
Detection Error for certain cards

### ISSUE THREAD

**Issue by kiralasani** [Masuzu/GBFPokerBot#64]
![image](https://cloud.githubusercontent.com/assets/23621041/21084970/1678fdb0-bfd9-11e6-9e97-98c2ba5c0af1.png)

**Comment by kiralasani** [comment]
Just an FYI, I did restart the bot and this happened again; but when i restarted GBF and the bot both, it worked. So it isn't happening anymore, but I wanted to report that it happens sometimes. (has happened before)

**Comment by Masuzu** [comment]
Got it, thank you for mentioning this. Should this happen, just discard the current end and try again with another hand.

**Comment by Masuzu** [comment]
Most of the time, the issue is that only 4 of the 5 cards are detected and depending on the positions of the cards, the bot will try to infer the positions of the non-detected 5th card. There is a particular configuration where the 5th card position can't be infered. I will fix this when I am back.

**Comment by Masuzu** [comment]
Some card coordinate detection improvements were added in version 2.3.0 https://poker-bot.azurewebsites.net/en/Home/PatchNotes
