### ISSUE TITLE
Suggestion : halo 

### ISSUE THREAD

**Issue by Yalzy** [Masuzu/GBFPokerBot#67]
can  we have halo angel bot too ?

**Comment by Masuzu** [comment]
Hi,

Such a bot could easily be extended to partake in cooperation room grinding/GW EX+ farming and would most likely take the form of a Chrome extension (potential anti-bot detection issues).
However, this would require an extensive amount of work to cover all the main character/character skills currently available in the game.
Therefore I am not sure if I will dedicate time to this, as I have other projects I have been brooding over lately.
That is a nice idea indeed :+1:

**Comment by Yalzy** [comment]
can you make like this video ?
you not need to make every single skills in game but use where to click like this

https://www.youtube.com/watch?v=DwLMhi7CDfQ

on this videos

at 0:05 you can see program where order on skill
http://i.imgur.com/PwjtMt3.png

if i checked on 

http://i.imgur.com/VRvrVIZ.png

in game will use this spell 

http://i.imgur.com/Z2oqflL.png

**Comment by Masuzu** [comment]
Thank you for the links. That's a pretty neat and intuitive UI.
Maybe I will give it some thought, but as for when, I do not know.

**Comment by Masuzu** [comment]
Will look into it in the upcoming days probably. Found some nice and interesting articles.

**Comment by Masuzu** [comment]
A quest farming bot for :
- special quests including Angel Halo
- Magna raids in their Hard form
- story quests
- free quests

is under development.
Beta version ETA: end of the week

**Comment by Masuzu** [comment]
Hello @Yalzy ,

Good news, here is a video featuring the beta version of a quest grinder-bot https://www.youtube.com/watch?v=6U0AdTji1tA
I will now work on a public release and proceed with more tests.

**Comment by Yalzy** [comment]
Wait for it :D  

can i setting skills i can will use in bot ?

**Comment by Masuzu** [comment]
I have been experiencing severe lag issues lately with the game.
Sometimes clicking on a character tooltip to display its skills will stay stuck and there is no other way around apart from reloading the page which is a pain. However, there are some workaround to deal with this.

The worst part is the random lagspikes/unresponsiveness of the page.

**Comment by Yalzy** [comment]
yup i think so :D  because   i see a lot new player

**Comment by Masuzu** [comment]
Making some progress:

Introducing new scripting feature, you will be able to nearly fully configure the behaviour of your party.
https://www.youtube.com/watch?v=UJmuqbfEaM0
Depending on your party and grid, this could be used to grind quests for materials (throwing in some treasure hunt stacks) or even Guild War Extreme and Nightmare modes.

3-hour demo - Cerberus Showdown - featuring Zooey grinding on her own Cerberus, the "event mode" new scripting features and page reloading after attacks:
https://www.youtube.com/watch?v=-xvDRwB4QEk

Likewise, Zooey will be able to grind Angel Halo on her own and do the Nightmare mode whenever it appears.

Letting the end-user create his own scripts offer a whole new level of customization, only bounded by your creativity.

**Comment by Masuzu** [comment]
Slime blasting mode is finally here!
For your enjoyment:
https://www.youtube.com/watch?v=GKHdazIbK_8

**Comment by Masuzu** [comment]
Even better than Angel Halo: automated Dimensional Halo farming! For your enjoyment:
https://www.youtube.com/watch?v=S_esoRe9xtM
