### ISSUE TITLE
media gallery at homepage

### ISSUE THREAD

**Issue by po456asd** [Masuzu/GBFPokerBot#69]
this is what you really want to show a nubula or just a mistake ?
It really look like come from my onedrive.
![image](https://cloud.githubusercontent.com/assets/13596788/21604065/ba361454-d1d3-11e6-831d-c8cd137bd50d.png)
![image](https://cloud.githubusercontent.com/assets/13596788/21604071/be64e000-d1d3-11e6-81e1-2f8b486b4b1c.png)
![image](https://cloud.githubusercontent.com/assets/13596788/21604074/c2e8a422-d1d3-11e6-8996-a57d25eec537.png)
![image](https://cloud.githubusercontent.com/assets/13596788/21604079/c8322a52-d1d3-11e6-924f-f3fe891a499e.png)
![image](https://cloud.githubusercontent.com/assets/13596788/21604083/cc42ed5c-d1d3-11e6-9833-0d205891ed90.png)

**Comment by Masuzu** [comment]
Yes, these are public domain images.
