### ISSUE TITLE
Bot taking wrong actions with '5 of a kind' hands

### ISSUE THREAD

**Issue by Yalzy** [Masuzu/GBFPokerBot#71]
http://i.imgur.com/6c5xf1K.png

i got 4 A and 1 joker

bot only keep joker :( fix please

**Comment by Masuzu** [comment]
Hi,

I identified the problem indeed. I will fix this withing 24 hours.

**Comment by Masuzu** [comment]
Fixed in version 2.4.0
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
