### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by Raiquia** [Masuzu/GBFPokerBot#72]
Im getting an error where it's saying my display is off, but I have all the settings set to what the requirements needs.

http://imgur.com/a/pwRad

**Comment by Masuzu** [comment]
You may want to relaunch the bot with another hand. If it still fails, then it is most likely a scaling issue again on your side. (The [Windows scaling settings](https://technet.microsoft.com/en-us/library/ff629368.aspx) are different from the [Browser zoom](https://support.google.com/chrome/answer/96810?hl=en)).
