### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by revenge13337** [Masuzu/GBFPokerBot#73]
Hi i was wondering if it was possible for the bot to stop after an x amount of time.

**Comment by Masuzu** [comment]
Hi,

It's already possible to do so. The parameter `TimeLimitInSeconds` in the configuration file GBFPokerBot.ini is designed for this purpose.

**Comment by revenge13337** [comment]
Thank you for the reply, is it possible to get a list of all parameters since my ini file does not have all the parameters.



Sent from myMail for iOS


Monday, January 16, 2017, 13:39 -0500 from Masuzu <notifications@github.com>:

Hi,

It's already possible to do so. The parameter TimeLimitInSeconds in the configuration file GBFPokerBot.ini is designed for this purpose.
