### ISSUE TITLE
option to disable Click feature (just only suggest the card)

### ISSUE THREAD

**Issue by zey71** [Masuzu/GBFPokerBot#76]
I know that this is very dumb request, but there's someone who want to click by himself to 100% accurate that will not trigger hidden anti-cheat system.

I knows that your click attempts is very secure enough. but for someone that has been strikes by suspension and don't want to risk have a (few) choice to go with.

Could you please add an feature that the bots will only suggest card in poker table for user to click (just in command line that's okay). and user have to click it by himself. This will help ppl that don't want to learn how to past the first section of poker table to get into double-up chance section.

Many thanks :)

**Comment by Masuzu** [comment]
Hello @zey71 ,
Sure thing I can do that. I will do that during the upcoming week-end!
Procrastination at its finest ._.

**Comment by Masuzu** [comment]
Release of this feature put on hold due to having a low priority.

**Comment by Masuzu** [comment]
A future release in on the way https://www.youtube.com/watch?v=tZK5wVQ3RU8&feature=youtu.be

**Comment by Masuzu** [comment]
New tool GBF Poker Advisor now live with version 2.5.0.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
