### ISSUE TITLE
Downloaded new Patch 2.5

### ISSUE THREAD

**Issue by blasterion** [Masuzu/GBFPokerBot#78]
Still says it's 2.4 and telling me to download 2.5

**Comment by darkzlevin** [comment]
I also have the same issue as blasterion

**Comment by channel99** [comment]
Same issue and now it's saying i'm an unregistered user.

**Comment by s6010694** [comment]
same issue here

**Comment by Masuzu** [comment]
Just closing the update window will make the bot proceed as usual, without any change. I will investigate the version mismatch.
In case it says you are an unregistered user, just proceed as usual and check your serial number on https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber

**Comment by Masuzu** [comment]
The version issue mismatch has been fixed.
