### ISSUE TITLE
Serial number updated incorrectly

### ISSUE THREAD

**Issue by Karbie** [Masuzu/GBFPokerBot#80]
Dear Masuzu, i seem to have updated my serial number on my PC to my account wrongly.

It seems like the first time i opened the serial generator my antivirus caused it to generate another set of keys.

Please advise if you can let me put in the correct serial number so that i can use the software on my PC
<img width="865" alt="capture" src="https://cloud.githubusercontent.com/assets/25868014/23095053/79f56590-f63e-11e6-9694-bdeb30c32e0d.PNG">

Thanks,
Barry

**Comment by Masuzu** [comment]
Hello @Karbie ,

Could you please send a mail to gbfpokerbot@gmail.com with your current serial number and the one you would like to use instead? I will make the update as soon as I have this information.
Thank you in advance,

Cheers
