### ISSUE TITLE
GBF hook initialization error

### ISSUE THREAD

**Issue by Kertys** [Masuzu/GBFPokerBot#82]
I'm running the app as instructed but it no longer works correctly since the 2.5.0 update. I'm getting a "GBF hook initialization error" dialog box that says it can't detect an active GBF window.

Screenshot attached.

![bot_bug02](https://cloud.githubusercontent.com/assets/26153191/23533176/dba2fc6a-ff64-11e6-9ac6-cf247c88a1bd.jpg)

**Comment by Masuzu** [comment]
Hello,

Did you make sure to change the language setting to "japanese"?
