### ISSUE TITLE
Changed my serial number and now it doesn't work. number generator gives wrong code in file

### ISSUE THREAD

**Issue by misericordia00** [Masuzu/GBFPokerBot#85]
Hi. I get an error whenever I try to use the new code. The serial number generator generates the wrong code.

**Comment by Masuzu** [comment]
Hi,
As long as the serial number you generated matches the one on this page https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber, there should be no issue.
You do not have to change manually your key.txt file. Should you have change your password, then you will need to redownload your key.txt file via this link https://poker-bot.azurewebsites.net/en/Account/GBFPokerBotSerialNumberGenerator

**Comment by misericordia00** [comment]
I renewed it on my account and it didn't work. (says GBFPokerBot.exe has
stopped working) But when I made a new account and did the trial, it
worked. So I'm not sure what's going on. Do you mind just giving me a month
on my new account instead?

**Comment by Masuzu** [comment]
Serial numbers are bound to computers and the feature to change your serial number allows you to reuse an active licence on other computer, with a cooldown of four days. Your key.txt file is bound to your account. If you somehow use the key.txt file from another person you will run into this kind of issue. Therefore I am afraid I can't do this.
