### ISSUE TITLE
Serial Key issue

### ISSUE THREAD

**Issue by vantrel** [Masuzu/GBFPokerBot#87]
Hey sorry I accidently changed the serial key by mistake and now I cant use it and have to wait for four days. Can you please help me?
![default](https://cloud.githubusercontent.com/assets/26290686/23733193/9c795eb4-04b2-11e7-86c3-6d52c086389c.PNG)

**Comment by Masuzu** [comment]
Hi,

Sure thing, I can. Please just send me the serial key you would like to use as plain text (so I can copy and paste it) as well as the email you used to register an account to gbfpokerbot@gmail.com

I will apply the change as soon as I can.

**Comment by eavictor** [comment]
Additional notice
The serial will change after Windows Universal update.
e.g. Win10 TH2-->Win10 RS1 or Win7 -->Win7 SP1

My suggestion is let user can change their serial key like 5 times in 14 days.
