### ISSUE TITLE
failed to find five cards

### ISSUE THREAD

**Issue by vvShio** [Masuzu/GBFPokerBot#88]
I have all the settings correct, however, it still gives me the Poker table hook error. Also tried many different hands.
![screenshot 1](https://cloud.githubusercontent.com/assets/26292633/23735765/4ef126f0-044d-11e7-97db-bb044668acc0.png)

**Comment by Masuzu** [comment]
Hi,

What people often forget to also do is to check their Windows and Chrome browser scaling:
https://www.thurrott.com/windows/windows-10/4597/windows-10-feature-focus-display-scaling

The card detection may not work either for Windows versions lower than 7.
