### ISSUE TITLE
Unable to use bot

### ISSUE THREAD

**Issue by Flamenze** [Masuzu/GBFPokerBot#89]
![doesn t work](https://cloud.githubusercontent.com/assets/26416517/23915790/09dc8ca8-0925-11e7-85a0-b9d6a98b4b3e.png)

So after about 2 weeks or so after I bought the license again, I've suddenly been unable to use it on either of my 2 laptops for unknown reasons. I've tried to change and sync the keys/serial numbers on both laptops and on the account yet neither of them would work. I do not know if I'm being retarded or something, please advise.

p.s  It worked only on 1 of the laptops last week, I don't know why. They both had the same serial number/key

**Comment by Masuzu** [comment]
Hello,

The version 2.6.0 introduced some changes which made the existing serial number generator deprecated. The one to be used should be the one provided with the version 2.6.0, which you can also get from this [https://drive.google.com/open?id=0Bxx3PpakQ2jGTkpYZ2tVaDZUQ0E](direct download link).

This serial number generator should normally not generate the same S/N on both computers, hopefully.

**Comment by Flamenze** [comment]
Strange, I've used version 2.6.0 in the picture above and redid the whole process again just to be sure. However, it's still saying it's unregistered.

**Comment by Masuzu** [comment]
Oh, I've just noticed it.
The key.txt file contents is *bot* the same as your serial number.

**Comment by Flamenze** [comment]
Ah, I just realized, the key file and serial number are 2 completely separate things, I just downloaded the key file from other settings and it works now. Sorry for wasting time with this stupid problem.

**Comment by Masuzu** [comment]
Awesome! All good then, no worries. I am here to help with these issues too :)
