### ISSUE TITLE
Unregistered user?

### ISSUE THREAD

**Issue by AkiLouki** [Masuzu/GBFPokerBot#91]
Keeps telling me that I'm unregistered when I run it but I have my license activated 
![image](https://cloud.githubusercontent.com/assets/26443078/23966273/ad55031c-09f5-11e7-8081-26c45b71d39c.png)

**Comment by AkiLouki** [comment]
and the serial number is also the same so it can't be that :/

**Comment by Masuzu** [comment]
Hi,
Your case might be similar to the one reported in https://github.com/Masuzu/GBFPokerBot/issues/89
Did you read the patch notes for the version 2.6 too: https://poker-bot.azurewebsites.net/en/Home/PatchNotes **(important note)**

**Comment by AkiLouki** [comment]
Thanks its working now. seems the key i had was for the previous un-updated serial so I just had to redownload the key ^^
