### ISSUE TITLE
Multiple Active Windows Error

### ISSUE THREAD

**Issue by RedEyes00** [Masuzu/GBFPokerBot#92]
I keep getting the following error: https://puu.sh/uMMF4/dae60816ed.png
I sometimes have another account open in incognito mode, but the error doesn't go away even after I close the 2nd window. I tried deleting the bot and redownloading the bot, but I still get the error. It's been like that for about a week.

**Comment by Masuzu** [comment]
Any other window with Grandblue Fantasy in its name (for instance the Grandblue Fantasy wikipedia) may cause this issue.
