### ISSUE TITLE
The bot can't find the ok button?

### ISSUE THREAD

**Issue by ekcs0915** [Masuzu/GBFPokerBot#93]
![](https://i.gyazo.com/f37868d83207fc6b98f4462159ffda3b.png)
Is there a way to resolve this issue?

**Comment by Yalzy** [comment]
minimize the dos screen

**Comment by Masuzu** [comment]
This happens when you start the bot while the OK button is not visible (probably you had the "Deal"/"Start" - if you use the japanese version of the game - active when you started the bot).
