### ISSUE TITLE
Payment Methods

### ISSUE THREAD

**Issue by lmaopat3** [Masuzu/GBFPokerBot#96]
Is there any other way I could subscribe to the pokerbot? I am not old enough to get a credit card nor a PayPal account. thanks!

**Comment by Masuzu** [comment]
I will think about it but if I can find a suitable provider for this.

**Comment by po456asd** [comment]
your country doesn't have virtual credit card provider?

**Comment by lmaopat3** [comment]
thank you, my country does but they all require the age of 18 with an existing credit card too

**Comment by Masuzu** [comment]
@lmaopat3 So which payment method would you rather use?

**Comment by po456asd** [comment]
have you try PayMaya? 
https://paymaya.com/

**Comment by lmaopat3** [comment]
@Masuzu i'm not sure as i have many problems here on my end.

@po456asd its not available in my area D:

**Comment by po456asd** [comment]
@lmaopat3 where you live?

**Comment by Masuzu** [comment]
Closing as this is derailing.
