### ISSUE TITLE
PokerBot not working 

### ISSUE THREAD

**Issue by Scrtblade** [Masuzu/GBFPokerBot#97]
![error](https://cloud.githubusercontent.com/assets/26537489/24091347/81d5e66c-0d82-11e7-8d9d-082ee9401cc0.png)

Hi,I am having a trouble with PokerBot 2.7.0_x64.Suddenly,It won't work when I start the program as the picture above(It used to work on 2.5.0_x64).I tried to redowload,update,and restart my computer but it still doesn't work
I hope I will get a reply from you as soon as possible. ^_^

**Comment by po456asd** [comment]
try reinstall this https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by Scrtblade** [comment]
Tried reinstalling a few times but it still doesn't work apparently

**Comment by po456asd** [comment]
did you restart computer already?

**Comment by po456asd** [comment]
another thing is try to switch to x86 ver

**Comment by Scrtblade** [comment]
Did like you suggest but it still won't work sadly(I restarted my PC before installing the x86 ver)

**Comment by Masuzu** [comment]
Hi,

This kind of Open CV related issue happen if you did not configure properly the scaling settings of Windows, Chrome and/or your in-game graphics.

**Comment by Scrtblade** [comment]
I extracted the files properly and now it is working
Thanks!
