### ISSUE TITLE
Problem with Poker version 2.7.0

### ISSUE THREAD

**Issue by AlucardSinon** [Masuzu/GBFPokerBot#98]
hello, I've become Full Members poker and satisfied with the version 2.5.0

But poker can not be used when it was updated to version 2.7.0 and I've put the key to poker folder ..

Notification that appears: Unregistered user, while in profile status Active License (expiration date 3/25/2017 6:20:35 AM)

my registered mail for your poker site is vampy.idol@gmail.com

Please help me to solve this problem..

Also, can I change the email on the poker site? my new email : alucard.sinon@gmail.com
![screenshot pokerbot 1](https://cloud.githubusercontent.com/assets/26538335/24092459/a41e4eac-0d0b-11e7-8cb6-170ffe093352.png)
![screenshot pokerbot 2](https://cloud.githubusercontent.com/assets/26538335/24092464/ad70e2e4-0d0b-11e7-8312-3ec79702290c.png)

**Comment by po456asd** [comment]
nah you need to gen the key from GBFPokerBotSerialNumberGenerator.exe in bot folder then add it on website.

go to 
![image](https://cloud.githubusercontent.com/assets/13596788/24093518/c5f5e104-0d86-11e7-8a92-4e91051f731f.png)
and use the key you got from GBFPokerBotSerialNumberGenerator.exe

**Comment by Masuzu** [comment]
Hi,

That is right indeed, what @po456asd said.
If you upgraded your version from 2.5.0 to 2.7.0 while skipping the version 2.6.0, you will need to update your serial number, as stated in the 2.6.0 patch notes.
You do not need to change your email.
